const ORDER_CONFIG = {
  MIN_ITEMS: 1,
  MAX_ITEMS: 50,
  MAX_QUANTITY_PER_ITEM: 1000,

  QR_TOKEN_BYTES: 24,

  SELLER_REVIEW_TIMEOUT_MINUTES: 120,
  PENDING_PAYMENT_RECONCILE_AFTER_MINUTES: 15,

  RIDER_ASSIGNED_REMINDER_MINUTES: 30,
  RIDER_ASSIGNED_TIMEOUT_MINUTES: 240,

  PICKED_UP_REMINDER_MINUTES: 45,

  ON_THE_WAY_REMINDER_MINUTES: 120,
  ON_THE_WAY_TIMEOUT_MINUTES: 720,

  DELIVERED_AUTO_COMPLETE_HOURS: 48,

  DELIVERY_ADDRESS_MIN_LENGTH: 10,
  DELIVERY_ADDRESS_MAX_LENGTH: 300,

  ALLOWED_STATUS_TRANSITIONS: {
    AWAITING_PAYMENT: ["PENDING_SELLER_REVIEW", "FAILED", "CANCELLED"],
    PENDING_SELLER_REVIEW: ["ACCEPTED", "REJECTED", "CANCELLED", "EXPIRED"],
    ACCEPTED: ["PREPARING", "READY_FOR_PICKUP", "RIDER_ASSIGNED", "CANCELLED"],
    PREPARING: ["READY_FOR_PICKUP", "RIDER_ASSIGNED", "CANCELLED"],
    READY_FOR_PICKUP: ["COMPLETED", "CANCELLED"],
    RIDER_ASSIGNED: ["PICKED_UP", "CANCELLED", "ACCEPTED"],
    PICKED_UP: ["ON_THE_WAY", "FAILED"],
    ON_THE_WAY: ["DELIVERED", "FAILED"],
    DELIVERED: ["COMPLETED"],
    COMPLETED: [],
    REJECTED: [],
    CANCELLED: [],
    EXPIRED: [],
    FAILED: [],
  },

  SUPPORTED_CURRENCIES: ["USD", "CDF"],

  PICKUP_ONLY_STATUSES: ["READY_FOR_PICKUP"],
  DELIVERY_ONLY_STATUSES: [
    "RIDER_ASSIGNED",
    "PICKED_UP",
    "ON_THE_WAY",
    "DELIVERED",
  ],

  CANCELLABLE_STATUSES: [
    "AWAITING_PAYMENT",
    "PENDING_SELLER_REVIEW",
    "ACCEPTED",
    "PREPARING",
    "READY_FOR_PICKUP",
    "RIDER_ASSIGNED",
  ],
};

module.exports = { ORDER_CONFIG };
