const SUBSCRIPTION_CONFIG = {
  PAST_DUE_GRACE_PERIOD_DAYS: 3,
  RENEWAL_ATTEMPT_DAYS_BEFORE_EXPIRY: 1,
  CANCELLATION_TAKES_EFFECT_AT_PERIOD_END: true,

  ALLOWED_STATUS_TRANSITIONS: {
    PENDING_PAYMENT: ["ACTIVE", "FAILED_PAYMENT"],
    ACTIVE: ["PAST_DUE", "CANCELED"],
    FAILED_PAYMENT: ["PENDING_PAYMENT"],
    PAST_DUE: ["ACTIVE", "EXPIRED"],
    EXPIRED: ["ACTIVE"],
    CANCELED: ["EXPIRED", "ACTIVE"],
  },
};

module.exports = { SUBSCRIPTION_CONFIG };
