const ACCOUNT_ACTION_TYPES = {
  BLOCKED: "BLOCKED",
  UNBLOCKED: "UNBLOCKED",
  ROLE_CHANGED: "ROLE_CHANGED",
  SOFT_DELETED: "SOFT_DELETED",
  RESTORED: "RESTORED",
  PERMANENTLY_DELETED: "PERMANENTLY_DELETED",
};

module.exports = { ACCOUNT_ACTION_TYPES };
