const SHOP_CONFIG = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 60,

  DESCRIPTION_MIN_LENGTH: 20,
  DESCRIPTION_MAX_LENGTH: 500,

  SUPPORTED_DELIVERY_CURRENCIES: ["USD", "CDF"],
  DELIVERY_FEE_MIN: {
    USD: 0.5,
    CDF: 1500,
  },
  DELIVERY_FEE_MAX: {
    USD: 2,
    CDF: 3600,
  },

  ALLOWED_STATUS_TRANSITIONS: {
    DRAFT: ["PUBLISHED"],
    PUBLISHED: ["SUSPENDED", "DRAFT"],
    SUSPENDED: ["PUBLISHED"],
  },

  DELETABLE_STATUSES: ["DRAFT", "SUSPENDED"],

  REQUIRES_ACTIVE_SUBSCRIPTION_TO_PUBLISH: true,
};

module.exports = { SHOP_CONFIG };
