import type { EndpointDoc } from "@/lib/types";

export type { HttpMethod, AuthRequirement, Param, ErrorExample, EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/auth";

const sampleUser = {
  id: "3f2a1c9e-7b41-4e2a-9c31-8e6b2d4f10aa",
  name: "Aline Mapendo",
  role: "BUYER",
  email: "aline@example.com",
  isEmailVerified: true,
  phone: "243812345678",
  isPhoneVerified: false,
  createdAt: "2026-01-14T10:32:00.000Z",
};

const unverifiedUser = { ...sampleUser, isEmailVerified: false };

export const AUTH_GROUPS = [
  "Account",
  "Login",
  "Password",
  "Two-Factor (TOTP)",
  "Passkeys",
  "Sessions",
  "Account Security",
  "Account Lockout Recovery",
] as const;

export const authEndpoints: EndpointDoc[] = [
  // --- Account ---
  {
    slug: "create-account",
    method: "POST",
    path: `${BASE}/create-account`,
    title: "Create account",
    group: "Account",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description:
      "Creates a new SwiftGoma account and emails a 6-character verification code to confirm ownership of the address. The account is unusable for login until the email is verified.",
    bodyParams: [
      { name: "name", type: "string", required: true, description: "Full name shown on the account." },
      { name: "email", type: "string", required: true, description: "Email address to verify and use for login." },
      { name: "role", type: "string", required: false, description: "One of BUYER, SELLER, RIDER. Defaults to BUYER." },
      { name: "locale", type: "string", required: false, description: "en or fr — controls the verification email language. Defaults to en." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: unverifiedUser },
    errorExamples: [
      { status: 422, code: "VALIDATION_ERROR", message: "Cette adresse e-mail est déjà utilisée." },
      { status: 429, code: "TOO_MANY_REQUESTS", message: "Trop de tentatives. Veuillez ralentir." },
    ],
    notes: [
      "Submitting the same unverified email again resends a new code instead of creating a duplicate account.",
      "Requests are screened for automated/bot traffic before hitting the rate limiter.",
    ],
  },
  {
    slug: "verify-email",
    method: "POST",
    path: `${BASE}/verify-email`,
    title: "Verify email",
    group: "Account",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description: "Confirms the verification code sent to a newly created account's email address.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "The email address being verified." },
      { name: "code", type: "string", required: true, description: "The verification code from the email." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
    errorExamples: [
      { status: 422, code: "OTP_INVALID", message: "Code de vérification invalide ou expiré." },
    ],
  },
  {
    slug: "resend-verification",
    method: "POST",
    path: `${BASE}/resend-verification`,
    title: "Resend verification email",
    group: "Account",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Issues a fresh verification code for an unverified account and re-sends it by email.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "The unverified account's email address." },
      { name: "locale", type: "string", required: false, description: "en or fr. Defaults to en." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: unverifiedUser },
    notes: ["Subject to a resend cooldown to prevent inbox flooding."],
  },
  {
    slug: "register-google",
    method: "POST",
    path: `${BASE}/register/google`,
    title: "Register with Google",
    group: "Account",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description: "Creates a SwiftGoma account from a verified Google ID token. Skips email verification since Google already confirmed the address.",
    bodyParams: [
      { name: "idToken", type: "string", required: true, description: "Google Sign-In ID token from the client SDK." },
      { name: "role", type: "string", required: false, description: "One of BUYER, SELLER, RIDER. Defaults to BUYER." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "On web, the access and refresh tokens are set as httpOnly cookies and are not present in the JSON body.",
      "On mobile clients (sending header x-client-type: mobile), the response body also includes accessToken and refreshToken.",
    ],
  },
  {
    slug: "register-apple",
    method: "POST",
    path: `${BASE}/register/apple`,
    title: "Register with Apple",
    group: "Account",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description: "Creates a SwiftGoma account from a verified Apple ID token. Skips email verification since Apple already confirmed the address.",
    bodyParams: [
      { name: "idToken", type: "string", required: true, description: "Sign in with Apple identity token from the client SDK." },
      { name: "name", type: "string", required: false, description: "Full name — only available from Apple on the very first authorization, so the client must capture and send it then." },
      { name: "role", type: "string", required: false, description: "One of BUYER, SELLER, RIDER. Defaults to BUYER." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "On web, the access and refresh tokens are set as httpOnly cookies and are not present in the JSON body.",
      "On mobile clients (sending header x-client-type: mobile), the response body also includes accessToken and refreshToken.",
    ],
  },
  // --- Login ---
  {
    slug: "login-google",
    method: "POST",
    path: `${BASE}/login/google`,
    title: "Log in with Google",
    group: "Login",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description: "Logs an existing user in using a Google ID token. If the account has TOTP enabled, this returns a pending token instead of a session.",
    bodyParams: [
      { name: "idToken", type: "string", required: true, description: "Google Sign-In ID token from the client SDK." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — pass pendingToken to POST /login/totp.",
    ],
  },
  {
    slug: "login-apple",
    method: "POST",
    path: `${BASE}/login/apple`,
    title: "Log in with Apple",
    group: "Login",
    auth: "none",
    rateLimit: "Account creation — tightly limited per IP",
    description: "Logs an existing user in using an Apple identity token. If the account has TOTP enabled, this returns a pending token instead of a session.",
    bodyParams: [
      { name: "idToken", type: "string", required: true, description: "Sign in with Apple identity token from the client SDK." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — pass pendingToken to POST /login/totp.",
    ],
  },
  {
    slug: "login-request-otp",
    method: "POST",
    path: `${BASE}/login/request-otp`,
    title: "Request a passwordless login code",
    group: "Login",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Sends a one-time login code by email for passwordless sign-in. Always returns the same generic response, whether or not the email is registered, to avoid leaking account existence.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Si un compte existe pour cet e-mail, un code de connexion a été envoyé." },
    },
  },
  {
    slug: "login-verify-otp",
    method: "POST",
    path: `${BASE}/login/verify-otp`,
    title: "Verify a passwordless login code",
    group: "Login",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Completes passwordless login using the code from POST /login/request-otp.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "code", type: "string", required: true, description: "The login code from the email." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    errorExamples: [
      { status: 401, code: "OTP_INVALID", message: "Code de vérification invalide ou expiré." },
    ],
    notes: [
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — pass pendingToken to POST /login/totp.",
      "On web, tokens are set as httpOnly cookies; on mobile, they're included in the response body.",
    ],
  },
  {
    slug: "login-request-otp-sms",
    method: "POST",
    path: `${BASE}/login/request-otp-sms`,
    title: "Request a passwordless login code by SMS",
    group: "Login",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Sends a one-time login code by SMS, as an alternative to the email code above. Requires the account to have a verified phone number. Always returns the same generic response, whether or not the phone number is registered.",
    bodyParams: [
      { name: "phone", type: "string", required: true, description: "Verified phone number on the account, e.g. +243999999999." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Si un compte existe avec ce numéro, un code de connexion a été envoyé." },
    },
  },
  {
    slug: "login-verify-otp-sms",
    method: "POST",
    path: `${BASE}/login/verify-otp-sms`,
    title: "Verify a passwordless login code sent by SMS",
    group: "Login",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Completes passwordless login using the code from POST /login/request-otp-sms.",
    bodyParams: [
      { name: "phone", type: "string", required: true, description: "The same phone number the code was requested for." },
      { name: "code", type: "string", required: true, description: "The login code from the SMS." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    errorExamples: [
      { status: 401, code: "OTP_INVALID", message: "Le code de connexion est incorrect." },
    ],
    notes: [
      "Uses its own OTP field on the account, separate from the email login code — requesting one doesn't invalidate the other.",
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — pass pendingToken to POST /login/totp.",
    ],
  },
  {
    slug: "login-password",
    method: "POST",
    path: `${BASE}/login/password`,
    title: "Log in with password",
    group: "Login",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Standard email + password login.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "password", type: "string", required: true, description: "Account password." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Identifiants invalides." },
    ],
    notes: [
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — pass pendingToken to POST /login/totp.",
      "A login-detected security email is sent for sign-ins from a new device or location.",
    ],
  },
  {
    slug: "login-totp",
    method: "POST",
    path: `${BASE}/login/totp`,
    title: "Complete login with a 2FA code",
    group: "Login",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Second step of login for accounts with TOTP enabled. Exchanges the pendingToken from an earlier login step, plus a current 6-digit authenticator code (or an unused backup code), for a real session.",
    bodyParams: [
      { name: "pendingToken", type: "string", required: true, description: "Short-lived token returned by a login endpoint when requiresTotp is true." },
      { name: "code", type: "string", required: true, description: "6-digit code from the authenticator app, or an unused backup code." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Code d'authentification invalide." },
    ],
  },
  // --- Passkeys ---
  {
    slug: "passkey-login-options",
    method: "POST",
    path: `${BASE}/passkey/login/options`,
    title: "Get passkey login options",
    group: "Passkeys",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Generates a WebAuthn assertion challenge for signing in with a passkey.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        challengeId: "8f1b2c3d-4e5f-6789-a0b1-c2d3e4f56789",
        options: { challenge: "base64url-challenge", rpId: "swiftgoma.com", allowCredentials: [] },
      },
    },
  },
  {
    slug: "passkey-login-verify",
    method: "POST",
    path: `${BASE}/passkey/login/verify`,
    title: "Verify passkey login",
    group: "Passkeys",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Completes passkey sign-in using the browser's WebAuthn assertion response.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "challengeId", type: "string", required: true, description: "challengeId from POST /passkey/login/options." },
      { name: "response", type: "object", required: true, description: "The WebAuthn assertion response object from navigator.credentials.get()." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "If two-factor authentication is also enabled, the response is { requiresTotp: true, pendingToken } instead.",
    ],
  },
  {
    slug: "passkey-register-options",
    method: "POST",
    path: `${BASE}/passkey/register/options`,
    title: "Get passkey registration options",
    group: "Passkeys",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Generates a WebAuthn attestation challenge to register a new passkey on the signed-in account.",
    successStatus: 200,
    responseExample: {
      success: true,
      data: { challenge: "base64url-challenge", rp: { name: "SwiftGoma", id: "swiftgoma.com" }, user: { id: "3f2a1c9e", name: "aline@example.com" } },
    },
  },
  {
    slug: "passkey-register-verify",
    method: "POST",
    path: `${BASE}/passkey/register/verify`,
    title: "Verify passkey registration",
    group: "Passkeys",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Confirms a newly created passkey using the browser's WebAuthn attestation response and saves it to the account.",
    bodyParams: [
      { name: "response", type: "object", required: true, description: "The WebAuthn attestation response object from navigator.credentials.create()." },
      { name: "deviceName", type: "string", required: false, description: "Label shown for this passkey in account settings." },
    ],
    successStatus: 201,
    responseExample: {
      success: true,
      data: { id: "pk_9a8b7c6d", deviceName: "Aline's iPhone", createdAt: "2026-02-01T09:12:00.000Z" },
    },
  },
  {
    slug: "passkey-list",
    method: "GET",
    path: `${BASE}/passkey`,
    title: "List passkeys",
    group: "Passkeys",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists every passkey registered on the signed-in account.",
    successStatus: 200,
    responseExample: {
      success: true,
      data: [
        { id: "pk_9a8b7c6d", deviceName: "Aline's iPhone", createdAt: "2026-02-01T09:12:00.000Z", lastUsedAt: "2026-02-14T18:30:00.000Z" },
      ],
    },
  },
  {
    slug: "passkey-delete",
    method: "DELETE",
    path: `${BASE}/passkey/:passkeyId`,
    title: "Remove a passkey",
    group: "Passkeys",
    auth: "bearer",
    rateLimit: "Session",
    description: "Removes a passkey from the signed-in account.",
    pathParams: [
      { name: "passkeyId", type: "string", required: true, description: "ID of the passkey to remove." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
  // --- Password ---
  {
    slug: "password-forgot",
    method: "POST",
    path: `${BASE}/password/forgot`,
    title: "Request a password reset",
    group: "Password",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Sends a password reset code by email. Always returns the same generic response, whether or not the email is registered, to avoid leaking account existence.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Si un compte existe pour cet e-mail, un code de réinitialisation a été envoyé." },
    },
  },
  {
    slug: "password-reset",
    method: "POST",
    path: `${BASE}/password/reset`,
    title: "Reset password",
    group: "Password",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Sets a new password using the code from POST /password/forgot.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Account email address." },
      { name: "code", type: "string", required: true, description: "The reset code from the email." },
      { name: "newPassword", type: "string", required: true, description: "New password. Minimum 8 characters." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
    errorExamples: [
      { status: 422, code: "OTP_INVALID", message: "Code de vérification invalide ou expiré." },
    ],
    notes: ["All existing sessions are revoked once the password is reset."],
  },
  {
    slug: "password-create",
    method: "POST",
    path: `${BASE}/password/create`,
    title: "Set a password",
    group: "Password",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Sets a password on an account that was created via Google or a passkey and doesn't have one yet.",
    bodyParams: [
      { name: "password", type: "string", required: true, description: "New password. Minimum 8 characters." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "password-update",
    method: "POST",
    path: `${BASE}/password/update`,
    title: "Change password",
    group: "Password",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Changes the password on the signed-in account. Requires the current password.",
    bodyParams: [
      { name: "currentPassword", type: "string", required: true, description: "The account's current password." },
      { name: "newPassword", type: "string", required: true, description: "New password. Minimum 8 characters." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Le mot de passe actuel est incorrect." },
    ],
    notes: ["Every other session (all devices except the current one) is revoked once the password changes."],
  },
  // --- Two-Factor (TOTP) ---
  {
    slug: "totp-setup",
    method: "POST",
    path: `${BASE}/totp/setup`,
    title: "Start 2FA setup",
    group: "Two-Factor (TOTP)",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Generates a new TOTP secret and QR code to scan into an authenticator app. Not yet enabled until confirmed with POST /totp/confirm.",
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        secret: "JBSWY3DPEHPK3PXP",
        otpauthUrl: "otpauth://totp/SwiftGoma:aline@example.com?secret=JBSWY3DPEHPK3PXP&issuer=SwiftGoma",
        qrCodeDataUrl: "data:image/png;base64,iVBORw0KGgoAAAANS...",
      },
    },
  },
  {
    slug: "totp-confirm",
    method: "POST",
    path: `${BASE}/totp/confirm`,
    title: "Confirm and enable 2FA",
    group: "Two-Factor (TOTP)",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Verifies the first code from the authenticator app and turns on two-factor authentication. Returns a one-time set of backup codes.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "6-digit code from the authenticator app." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        enabled: true,
        backupCodes: ["7K2M-9QXZ", "P4RT-6VDC", "L1WY-3JFB", "H8NQ-0ZKS", "D5GE-2MTA"],
      },
    },
    notes: ["Backup codes are shown once — store them somewhere safe. Each one can be used a single time in place of a TOTP code."],
  },
  {
    slug: "totp-disable",
    method: "POST",
    path: `${BASE}/totp/disable`,
    title: "Disable 2FA",
    group: "Two-Factor (TOTP)",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Turns off two-factor authentication on the signed-in account.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "A current 6-digit code or an unused backup code." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { enabled: false } },
    notes: ["All other sessions are revoked when 2FA is disabled, as a safety precaution."],
  },
  {
    slug: "totp-regenerate-backup-codes",
    method: "POST",
    path: `${BASE}/totp/regenerate-backup-codes`,
    title: "Regenerate backup codes",
    group: "Two-Factor (TOTP)",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Invalidates all existing backup codes and issues a fresh set.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "A current 6-digit code or an unused backup code." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { backupCodes: ["3F9K-1QLM", "A6DP-8ZRT", "Y2WX-4NHC", "B7VE-0JGS", "Q5UM-6KFA"] },
    },
  },
  // --- Sessions ---
  {
    slug: "refresh-token",
    method: "POST",
    path: `${BASE}/refresh-token`,
    title: "Refresh access token",
    group: "Sessions",
    auth: "none",
    rateLimit: "Session refresh",
    description: "Exchanges a valid refresh token for a new access token. On web this reads the refresh token from an httpOnly cookie automatically; mobile clients pass it explicitly.",
    bodyParams: [
      { name: "refreshToken", type: "string", required: false, description: "Required for mobile clients (header x-client-type: mobile). Web clients rely on the refresh-token cookie instead." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Session invalide ou expirée." },
    ],
  },
  {
    slug: "me",
    method: "GET",
    path: `${BASE}/me`,
    title: "Get current user",
    group: "Sessions",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns the profile of the currently signed-in user.",
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "logout",
    method: "POST",
    path: `${BASE}/logout`,
    title: "Log out",
    group: "Sessions",
    auth: "bearer",
    rateLimit: "Session",
    description: "Revokes the current session and clears the auth cookies on web.",
    successStatus: 200,
    responseExample: { success: true, data: { loggedOut: true } },
  },
  {
    slug: "logout-all",
    method: "POST",
    path: `${BASE}/logout-all`,
    title: "Log out everywhere",
    group: "Sessions",
    auth: "bearer",
    rateLimit: "Session",
    description: "Revokes every session on the account, including the current one.",
    successStatus: 200,
    responseExample: { success: true, data: { revokedCount: 3 } },
  },
  {
    slug: "sessions-list",
    method: "GET",
    path: `${BASE}/sessions`,
    title: "List active sessions",
    group: "Sessions",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists every active session on the account, with the current one flagged.",
    successStatus: 200,
    responseExample: {
      success: true,
      data: [
        { id: "sess_1a2b3c", deviceName: "Chrome on macOS", ipAddress: "154.72.10.4", isCurrent: true, createdAt: "2026-02-14T18:30:00.000Z" },
        { id: "sess_4d5e6f", deviceName: "SwiftGoma iOS App", ipAddress: "41.243.8.90", isCurrent: false, createdAt: "2026-02-01T09:12:00.000Z" },
      ],
    },
  },
  {
    slug: "sessions-revoke",
    method: "DELETE",
    path: `${BASE}/sessions/:sessionId`,
    title: "Revoke a session",
    group: "Sessions",
    auth: "bearer",
    rateLimit: "Session",
    description: "Revokes a single session by ID — useful for signing out a specific device remotely.",
    pathParams: [
      { name: "sessionId", type: "string", required: true, description: "ID of the session to revoke, from GET /sessions." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { revoked: true } },
  },
  // --- Account Security ---
  {
    slug: "account-activity",
    method: "GET",
    path: `${BASE}/activity`,
    title: "List account activity",
    group: "Account Security",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns a paginated, durable history of security-relevant events on the account — sign-ins, password changes, two-factor changes, passkey and session changes, and account-secured events.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Defaults to 20, max 100." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        activity: [
          { id: "act_1a2b3c", action: "LOGIN_SUCCESS", createdAt: "2026-02-14T18:30:00.000Z", metadata: { ip: "154.72.10.4", userAgent: "Mozilla/5.0", isNewDevice: false }, isSelfInitiated: true },
          { id: "act_4d5e6f", action: "PASSWORD_CHANGED", createdAt: "2026-02-10T09:12:00.000Z", metadata: null, isSelfInitiated: true },
        ],
        pagination: { page: 1, limit: 20, total: 2, totalPages: 1 },
      },
    },
    notes: [
      "Only a fixed allowlist of self-explanatory action types is returned — internal audit rows unrelated to the account owner's own security are filtered out.",
      "LOGIN_SUCCESS entries include isNewDevice, set by comparing a normalized browser/OS/device fingerprint against every prior session, so an alert (and the secure-account link below) only fires for genuinely unrecognized devices.",
    ],
  },
  {
    slug: "secure-account-request-otp",
    method: "POST",
    path: `${BASE}/secure-account/request-otp`,
    title: "Request a code to secure the account",
    group: "Account Security",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Sends a confirmation code to the account's primary email — the first step of the in-app \"Secure my account\" flow, used when a signed-in user suspects their own account has been compromised.",
    successStatus: 200,
    responseExample: { success: true, data: { message: "Code envoyé." } },
  },
  {
    slug: "secure-account-confirm",
    method: "POST",
    path: `${BASE}/secure-account/confirm`,
    title: "Confirm and secure the account",
    group: "Account Security",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Confirms the code from POST /secure-account/request-otp and immediately locks down the account: revokes every session (including the current one), clears the password, and removes any two-factor method and passkeys. Auth cookies are cleared on web.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "The confirmation code from the account's email." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Compte sécurisé. Toutes les sessions ont été déconnectées." } },
    notes: [
      "This is the same lockdown used by the email deep-link and phone-recovery flows below — only the entry point differs.",
      "Sends a confirmation email (and, if a verified secondary email exists, a copy to that address too) once the lockdown completes.",
    ],
  },
  {
    slug: "secure-account-confirm-link",
    method: "POST",
    path: `${BASE}/secure-account/confirm-link`,
    title: "Secure the account via an emailed link",
    group: "Account Security",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Confirms a signed, single-use token embedded in security alert emails (e.g. the new-sign-in-detected email) and runs the same lockdown as POST /secure-account/confirm. Reachable without an active session, since possessing the token is itself the proof of identity.",
    bodyParams: [
      { name: "token", type: "string", required: true, description: "The token from the \"Secure your account\" link in the email." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Compte sécurisé. Toutes les sessions ont été déconnectées." } },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Ce lien est invalide, a expiré, ou a déjà été utilisé." },
    ],
    notes: [
      "The token expires after 30 minutes and is single-use, tracked independently of its own JWT expiry.",
    ],
  },
  // --- Account Lockout Recovery ---
  {
    slug: "account-recovery-phone-request",
    method: "POST",
    path: `${BASE}/account-recovery/phone/request`,
    title: "Request account recovery by phone",
    group: "Account Lockout Recovery",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "For a user who can't sign in at all (lost password, lost authenticator, no backup codes) — sends an SMS code to a verified phone number on the account. Always returns the same generic response, whether or not the number is registered.",
    bodyParams: [
      { name: "phone", type: "string", required: true, description: "Verified phone number on the account." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Si un compte existe avec ce numéro, un code de récupération a été envoyé." },
    },
    notes: [
      "Uses its own OTP field, separate from both login-by-SMS and any other pending code, so a stuck recovery attempt can't collide with an in-progress sign-in.",
    ],
  },
  {
    slug: "account-recovery-phone-confirm",
    method: "POST",
    path: `${BASE}/account-recovery/phone/confirm`,
    title: "Confirm account recovery by phone",
    group: "Account Lockout Recovery",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Confirms the code from POST /account-recovery/phone/request and runs the same full lockdown as POST /secure-account/confirm — every session revoked, password cleared, two-factor and passkeys removed. Does not sign the user in; they sign in fresh afterward and set a new password.",
    bodyParams: [
      { name: "phone", type: "string", required: true, description: "The same phone number the code was requested for." },
      { name: "code", type: "string", required: true, description: "The recovery code from the SMS." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Compte sécurisé. Toutes les sessions ont été déconnectées." } },
    errorExamples: [
      { status: 404, code: "NOT_FOUND", message: "Aucun compte trouvé avec ce numéro." },
    ],
    notes: [
      "A soft-deleted account is deliberately excluded here and returns NOT_FOUND — that case belongs to the separate account-deletion recovery flow, not this one.",
    ],
  },
];

