import type { EndpointDoc } from "@/lib/types";

const PLANS_BASE = "/api/v1/plans";
const SUB_BASE = "/api/v1/subscriptions";
const ADMIN_SUB_BASE = "/api/v1/subscriptions/admin";
const INVOICE_BASE = "/api/v1/invoices";
const ADMIN_INVOICE_BASE = "/api/v1/invoices/admin";

const samplePlan = {
  id: "plan_starter",
  slug: "starter",
  name: "Starter",
  maxProducts: 20,
  maxPhotosPerProduct: 5,
  maxShops: 1,
  prioritySupport: false,
  isActive: true,
  sortOrder: 0,
  prices: [
    { billingCycle: "MONTHLY", currency: "USD", amount: "10.00" },
    { billingCycle: "YEARLY", currency: "USD", amount: "100.00" },
  ],
};

const sampleSubscription = {
  id: "sub_9c8d7e",
  sellerProfileId: "sp_2b3c4d",
  planId: "plan_starter",
  billingCycle: "MONTHLY",
  currency: "USD",
  status: "ACTIVE",
  currentPeriodStart: "2026-02-01T00:00:00.000Z",
  currentPeriodEnd: "2026-03-01T00:00:00.000Z",
};

const sampleSubscriptionPayment = {
  id: "subpay_1a2b3c",
  subscriptionId: "sub_9c8d7e",
  depositId: "SWG-DEP-9f8e7d6c5b4a3210",
  amount: "10.00",
  currency: "USD",
  status: "SUCCEEDED",
  paidAt: "2026-02-01T09:05:00.000Z",
};

const sampleInvoice = {
  id: "inv_1a2b3c",
  sellerProfileId: "sp_2b3c4d",
  number: "SWG-INV-2026-0042",
  amount: "10.00",
  currency: "USD",
  issuedAt: "2026-02-01T09:05:00.000Z",
  pdfUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/invoices/swg-inv-2026-0042.pdf",
};

export const BILLING_GROUPS = ["Plans", "Subscriptions", "Invoices"] as const;

export const billingEndpoints: EndpointDoc[] = [
  // --- Plans ---
  {
    slug: "list-plans",
    method: "GET",
    path: PLANS_BASE,
    title: "List plans",
    group: "Plans",
    auth: "none",
    rateLimit: "Public",
    description: "Lists subscription plans available to sellers.",
    queryParams: [{ name: "includeInactive", type: "boolean", required: false, description: "Staff use only in practice — defaults to false." }],
    successStatus: 200,
    responseExample: { success: true, data: [samplePlan] },
  },
  {
    slug: "get-plan",
    method: "GET",
    path: `${PLANS_BASE}/:id`,
    title: "Get plan",
    group: "Plans",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a single plan by ID.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Plan ID." }],
    successStatus: 200,
    responseExample: { success: true, data: samplePlan },
  },
  {
    slug: "get-plan-by-slug",
    method: "GET",
    path: `${PLANS_BASE}/slug/:slug`,
    title: "Get plan by slug",
    group: "Plans",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a single plan by its slug.",
    pathParams: [{ name: "slug", type: "string", required: true, description: "Plan slug, e.g. starter." }],
    successStatus: 200,
    responseExample: { success: true, data: samplePlan },
  },
  {
    slug: "create-plan",
    method: "POST",
    path: PLANS_BASE,
    title: "Create plan",
    group: "Plans",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Creates a new subscription plan. Admin-only.",
    bodyParams: [
      { name: "slug", type: "string", required: true, description: "" },
      { name: "name", type: "string", required: true, description: "" },
      { name: "maxProducts", type: "number", required: true, description: "" },
      { name: "maxPhotosPerProduct", type: "number", required: true, description: "" },
      { name: "maxShops", type: "number", required: true, description: "" },
      { name: "prioritySupport", type: "boolean", required: false, description: "" },
      { name: "sortOrder", type: "number", required: false, description: "" },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { ...samplePlan, prices: [] } },
  },
  {
    slug: "update-plan",
    method: "PUT",
    path: `${PLANS_BASE}/:id`,
    title: "Update plan",
    group: "Plans",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Updates a plan's limits or active state. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Plan ID." }],
    bodyParams: [
      { name: "name", type: "string", required: false, description: "" },
      { name: "maxProducts", type: "number", required: false, description: "" },
      { name: "maxPhotosPerProduct", type: "number", required: false, description: "" },
      { name: "maxShops", type: "number", required: false, description: "" },
      { name: "prioritySupport", type: "boolean", required: false, description: "" },
      { name: "isActive", type: "boolean", required: false, description: "" },
      { name: "sortOrder", type: "number", required: false, description: "" },
    ],
    successStatus: 200,
    responseExample: { success: true, data: samplePlan },
  },
  {
    slug: "update-plan-price",
    method: "PUT",
    path: `${PLANS_BASE}/:id/prices`,
    title: "Update plan price",
    group: "Plans",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Sets the price for one billing cycle and currency on a plan. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Plan ID." }],
    bodyParams: [
      { name: "billingCycle", type: "string", required: true, description: "MONTHLY or YEARLY." },
      { name: "currency", type: "string", required: true, description: "USD or CDF." },
      { name: "amount", type: "number", required: true, description: "" },
    ],
    successStatus: 200,
    responseExample: { success: true, data: samplePlan.prices[0] },
  },
  {
    slug: "set-plan-active",
    method: "POST",
    path: `${PLANS_BASE}/:id/active`,
    title: "Set plan active state",
    group: "Plans",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Enables or disables a plan for new subscriptions. Existing subscribers on a disabled plan aren't affected. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Plan ID." }],
    bodyParams: [{ name: "isActive", type: "boolean", required: true, description: "" }],
    successStatus: 200,
    responseExample: { success: true, data: samplePlan },
  },
  // --- Subscriptions ---
  {
    slug: "subscribe",
    method: "POST",
    path: SUB_BASE,
    title: "Subscribe",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Payment",
    description: "Subscribes the seller to a plan and initiates a PawaPay deposit for the first payment.",
    bodyParams: [
      { name: "planId", type: "string", required: true, description: "" },
      { name: "billingCycle", type: "string", required: true, description: "MONTHLY or YEARLY." },
      { name: "currency", type: "string", required: true, description: "USD or CDF." },
      { name: "payerPhoneNumber", type: "string", required: true, description: "" },
      { name: "country", type: "string", required: true, description: "" },
      { name: "provider", type: "string", required: true, description: "Mobile money provider code." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { subscription: { ...sampleSubscription, status: "PENDING" }, payment: { ...sampleSubscriptionPayment, status: "PENDING" }, depositId: "SWG-DEP-9f8e7d6c5b4a3210" } },
    notes: ["The subscription activates once PawaPay confirms the deposit — either via webhook, or by polling POST /payments/:depositId/check-status."],
  },
  {
    slug: "upgrade-subscription",
    method: "POST",
    path: `${SUB_BASE}/upgrade`,
    title: "Upgrade subscription",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Payment",
    description: "Switches the seller to a different plan, charging the new plan's price the same way as subscribing.",
    bodyParams: [
      { name: "newPlanId", type: "string", required: true, description: "" },
      { name: "billingCycle", type: "string", required: true, description: "MONTHLY or YEARLY." },
      { name: "currency", type: "string", required: true, description: "USD or CDF." },
      { name: "payerPhoneNumber", type: "string", required: true, description: "" },
      { name: "country", type: "string", required: true, description: "" },
      { name: "provider", type: "string", required: true, description: "" },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { subscription: sampleSubscription, payment: sampleSubscriptionPayment, depositId: "SWG-DEP-1a2b3c4d5e6f7890" } },
  },
  {
    slug: "get-my-subscription",
    method: "GET",
    path: `${SUB_BASE}/me`,
    title: "Get my subscription",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Returns the signed-in seller's current subscription.",
    successStatus: 200,
    responseExample: { success: true, data: sampleSubscription },
  },
  {
    slug: "get-my-subscription-payments",
    method: "GET",
    path: `${SUB_BASE}/me/payments`,
    title: "Get my payment history",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Lists past subscription payment attempts.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { payments: [sampleSubscriptionPayment], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "cancel-subscription",
    method: "POST",
    path: `${SUB_BASE}/me/cancel`,
    title: "Cancel subscription",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Cancels the seller's subscription. Access typically continues until the end of the current billing period.",
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleSubscription, status: "CANCELED" } },
  },
  {
    slug: "reactivate-subscription",
    method: "POST",
    path: `${SUB_BASE}/me/reactivate`,
    title: "Reactivate subscription",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Reverses a cancellation while still within the paid period — no new charge.",
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleSubscription, status: "ACTIVE" } },
  },
  {
    slug: "check-subscription-payment-status",
    method: "POST",
    path: `${SUB_BASE}/payments/:depositId/check-status`,
    title: "Check payment status",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Payment",
    description: "Polls PawaPay for a deposit's current status and, if it has resolved, updates the subscription accordingly — a fallback for when the webhook hasn't landed yet.",
    pathParams: [{ name: "depositId", type: "string", required: true, description: "Must belong to the signed-in seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { subscription: sampleSubscription, payment: sampleSubscriptionPayment, pawapayStatus: "COMPLETED" } },
  },
  {
    slug: "get-subscription-stats",
    method: "GET",
    path: `${SUB_BASE}/stats`,
    title: "Get subscription stats",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns subscription counts by plan and status. Staff-only.",
    successStatus: 200,
    responseExample: { success: true, data: { totalActive: 128, byPlan: { starter: 90, growth: 38 }, byStatus: { ACTIVE: 128, CANCELED: 12, PAST_DUE: 4 } } },
  },
  {
    slug: "get-subscription-revenue",
    method: "GET",
    path: `${SUB_BASE}/revenue`,
    title: "Get subscription revenue",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns subscription revenue totals. Staff-only.",
    successStatus: 200,
    responseExample: { success: true, data: { totals: [{ currency: "USD", amount: "1280.00" }] } },
  },
  {
    slug: "admin-list-subscriptions",
    method: "GET",
    path: ADMIN_SUB_BASE,
    title: "List all subscriptions",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Lists subscriptions across every seller. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "Filter by subscription status." },
      { name: "planId", type: "string", required: false, description: "Filter by plan." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { subscriptions: [sampleSubscription], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "admin-get-subscription",
    method: "GET",
    path: `${ADMIN_SUB_BASE}/:id`,
    title: "Get subscription detail",
    group: "Subscriptions",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns full detail for one subscription. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Subscription ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleSubscription },
  },
  // --- Invoices ---
  {
    slug: "get-my-invoices",
    method: "GET",
    path: `${INVOICE_BASE}/me`,
    title: "List my invoices",
    group: "Invoices",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists invoices issued to the signed-in seller for their subscription payments.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { invoices: [sampleInvoice], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "download-my-invoice",
    method: "GET",
    path: `${INVOICE_BASE}/me/download/:id`,
    title: "Download my invoice",
    group: "Invoices",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns the invoice's PDF download link.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to the signed-in seller." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleInvoice },
  },
  {
    slug: "get-invoice-stats",
    method: "GET",
    path: `${INVOICE_BASE}/stats`,
    title: "Get invoice stats",
    group: "Invoices",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns aggregate invoice totals. Staff-only.",
    successStatus: 200,
    responseExample: { success: true, data: { totalIssued: 340, totals: [{ currency: "USD", amount: "3400.00" }] } },
  },
  {
    slug: "admin-list-invoices",
    method: "GET",
    path: ADMIN_INVOICE_BASE,
    title: "List all invoices",
    group: "Invoices",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Lists invoices across every seller. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "sellerProfileId", type: "string", required: false, description: "Filter by seller." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { invoices: [sampleInvoice], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "admin-download-invoice",
    method: "GET",
    path: `${ADMIN_INVOICE_BASE}/:id`,
    title: "Download any invoice",
    group: "Invoices",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns any invoice's PDF download link, regardless of seller. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Invoice ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleInvoice },
  },
];
