import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/blog";

const samplePost = {
  id: "post_1a2b3c",
  authorId: "9f8e7d6c",
  title: "Comment bien démarrer sur SwiftGoma",
  slug: "comment-bien-demarrer-sur-swiftgoma",
  excerpt: "Un guide rapide pour les nouveaux vendeurs.",
  content: "<p>Contenu de l'article…</p>",
  coverImageUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/blog/demarrer.jpg",
  status: "PUBLISHED",
  publishedAt: "2026-02-01T09:00:00.000Z",
};

export const BLOG_GROUPS = ["Blog"] as const;

export const blogEndpoints: EndpointDoc[] = [
  {
    slug: "list-blog-posts",
    method: "GET",
    path: BASE,
    title: "List posts",
    group: "Blog",
    auth: "none",
    rateLimit: "Public",
    description: "Lists published blog posts.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { posts: [samplePost], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "get-blog-post-by-slug",
    method: "GET",
    path: `${BASE}/slug/:slug`,
    title: "Get post",
    group: "Blog",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a single published post.",
    pathParams: [{ name: "slug", type: "string", required: true, description: "Post slug." }],
    successStatus: 200,
    responseExample: { success: true, data: samplePost },
  },
  {
    slug: "admin-list-blog-posts",
    method: "GET",
    path: `${BASE}/admin`,
    title: "List all posts",
    group: "Blog",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists every post regardless of status. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "DRAFT or PUBLISHED." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { posts: [samplePost], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "admin-get-blog-post",
    method: "GET",
    path: `${BASE}/admin/:id`,
    title: "Get post (any status)",
    group: "Blog",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Returns a post regardless of status, for editing. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Post ID." }],
    successStatus: 200,
    responseExample: { success: true, data: samplePost },
  },
  {
    slug: "create-blog-post",
    method: "POST",
    path: BASE,
    title: "Create post",
    group: "Blog",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Creates a blog post. Staff-only.",
    bodyParams: [
      { name: "title", type: "string", required: true, description: "" },
      { name: "excerpt", type: "string", required: true, description: "" },
      { name: "content", type: "string", required: true, description: "HTML content." },
      { name: "status", type: "string", required: false, description: "DRAFT or PUBLISHED. Defaults to DRAFT." },
      { name: "coverImage", type: "file", required: false, description: "" },
    ],
    successStatus: 201,
    responseExample: { success: true, data: samplePost },
  },
  {
    slug: "update-blog-post",
    method: "PUT",
    path: `${BASE}/:id`,
    title: "Update post",
    group: "Blog",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Updates a post's content, status, or cover image. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Post ID." }],
    bodyParams: [
      { name: "title", type: "string", required: false, description: "" },
      { name: "excerpt", type: "string", required: false, description: "" },
      { name: "content", type: "string", required: false, description: "" },
      { name: "status", type: "string", required: false, description: "DRAFT or PUBLISHED." },
      { name: "coverImage", type: "file", required: false, description: "Replaces the existing cover image." },
      { name: "removeCoverImage", type: "boolean", required: false, description: "Removes the cover image without replacing it." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: samplePost },
  },
  {
    slug: "delete-blog-post",
    method: "DELETE",
    path: `${BASE}/:id`,
    title: "Delete post",
    group: "Blog",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Deletes a blog post. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Post ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
];
