import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/expenses";

const sampleExpense = {
  id: "exp_1a2b3c",
  reference: "SWG-EXP-2026-0014",
  title: "Renouvellement hébergement serveur",
  description: "Facture mensuelle du fournisseur d'hébergement.",
  category: "UTILITIES",
  amount: "150.00",
  currency: "USD",
  status: "PENDING",
  incurredAt: "2026-02-10T00:00:00.000Z",
  vendorName: "CloudHost SARL",
  vendorPhone: "243812345678",
  countryCode: "CD",
  providerName: "MTN_MOMO_COD",
  createdBy: { id: "9f8e7d6c", name: "Marie Kanku" },
  approvedBy: null,
  createdAt: "2026-02-10T08:00:00.000Z",
};

export const EXPENSE_GROUPS = ["Expenses"] as const;

export const expenseEndpoints: EndpointDoc[] = [
  {
    slug: "get-expense-meta",
    method: "GET",
    path: `${BASE}/meta`,
    title: "Get expense categories",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns the list of valid expense categories.",
    successStatus: 200,
    responseExample: {
      success: true,
      data: { categories: ["OPERATIONS", "MARKETING", "PAYROLL", "LEGAL", "TRAVEL", "UTILITIES", "EQUIPMENT", "OTHER"] },
    },
  },
  {
    slug: "list-expenses",
    method: "GET",
    path: BASE,
    title: "List expenses",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Lists expenses.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 50. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "PENDING, REJECTED, PROCESSING, COMPLETED, or FAILED." },
      { name: "category", type: "string", required: false, description: "" },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { expenses: [sampleExpense], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "get-expense",
    method: "GET",
    path: `${BASE}/:id`,
    title: "Get expense",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns one expense's detail.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleExpense },
  },
  {
    slug: "create-expense",
    method: "POST",
    path: BASE,
    title: "Create expense",
    group: "Expenses",
    auth: "bearer",
    roles: ["ACCOUNTANT"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Records a new expense, pending admin approval.",
    bodyParams: [
      { name: "title", type: "string", required: true, description: "" },
      { name: "description", type: "string", required: false, description: "" },
      { name: "category", type: "string", required: true, description: "One of the categories from GET /meta." },
      { name: "amount", type: "number", required: true, description: "" },
      { name: "currency", type: "string", required: true, description: "" },
      { name: "incurredAt", type: "string", required: true, description: "ISO date the expense was incurred." },
      { name: "vendorName", type: "string", required: true, description: "Payout beneficiary name." },
      { name: "vendorPhone", type: "string", required: true, description: "Payout mobile money number." },
      { name: "countryCode", type: "string", required: true, description: "" },
      { name: "providerName", type: "string", required: true, description: "Mobile money provider code." },
      { name: "customerMessage", type: "string", required: false, description: "4–22 alphanumeric characters, shown on the payout." },
      { name: "receipt", type: "file", required: false, description: "Receipt image or PDF." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleExpense },
  },
  {
    slug: "update-expense",
    method: "PUT",
    path: `${BASE}/:id`,
    title: "Update expense",
    group: "Expenses",
    auth: "bearer",
    roles: ["ACCOUNTANT"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Updates an expense. Only allowed before it's been paid out.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    bodyParams: [
      { name: "title", type: "string", required: false, description: "" },
      { name: "description", type: "string", required: false, description: "" },
      { name: "category", type: "string", required: false, description: "" },
      { name: "amount", type: "number", required: false, description: "" },
      { name: "currency", type: "string", required: false, description: "" },
      { name: "incurredAt", type: "string", required: false, description: "" },
      { name: "vendorName", type: "string", required: false, description: "" },
      { name: "vendorPhone", type: "string", required: false, description: "" },
      { name: "countryCode", type: "string", required: false, description: "" },
      { name: "providerName", type: "string", required: false, description: "" },
      { name: "customerMessage", type: "string", required: false, description: "" },
      { name: "receipt", type: "file", required: false, description: "Replaces the existing receipt." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleExpense },
  },
  {
    slug: "reject-expense",
    method: "POST",
    path: `${BASE}/:id/reject`,
    title: "Reject expense",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Rejects a pending expense. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "" }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleExpense, status: "REJECTED" } },
  },
  {
    slug: "request-expense-approval",
    method: "POST",
    path: `${BASE}/:id/approve/request`,
    title: "Request approval",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout OTP",
    description: "First step of paying out an expense — the same OTP-gated pattern used across the platform's finance tooling. Validates the expense and emails a code. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Un code de vérification a été envoyé à admin@swiftgoma.com.", expiresInMinutes: 5 },
    },
  },
  {
    slug: "resend-expense-approval",
    method: "POST",
    path: `${BASE}/:id/approve/resend`,
    title: "Resend approval code",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout OTP resend",
    description: "Re-sends the verification code if the original expired or wasn't received. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Un nouveau code de vérification a été envoyé." } },
  },
  {
    slug: "confirm-expense-approval",
    method: "POST",
    path: `${BASE}/:id/approve/confirm`,
    title: "Confirm approval",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout confirm",
    description: "Submits the code and sends the expense payout via PawaPay. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Expense ID." }],
    bodyParams: [{ name: "code", type: "string", required: true, description: "The verification code from the email." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleExpense, status: "PROCESSING" } },
  },
  {
    slug: "export-expenses-csv",
    method: "GET",
    path: `${BASE}/export/csv`,
    title: "Export expenses (CSV)",
    group: "Expenses",
    auth: "bearer",
    roles: ["ADMIN", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Exports expenses as a CSV file, respecting the same filters as the list endpoint.",
    queryParams: [
      { name: "status", type: "string", required: false, description: "" },
      { name: "category", type: "string", required: false, description: "" },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Returns text/csv — not a JSON body." } },
  },
];
