import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/seller/kyc";

const sampleKyc = {
  id: "kyc_8f1e2a",
  sellerProfileId: "sp_2b3c4d",
  idDocumentType: "NATIONAL_ID",
  idDocumentUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/kyc/id-aline.jpg",
  proofOfAddressUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/kyc/address-aline.jpg",
  selfieUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/kyc/selfie-aline.jpg",
  rccmNumber: null,
  rccmDocumentUrl: null,
  status: "PENDING",
  createdAt: "2026-01-06T09:00:00.000Z",
};

const sampleKycDetail = {
  ...sampleKyc,
  sellerProfile: {
    id: "sp_2b3c4d",
    businessName: "Boutique Aline",
    userId: "3f2a1c9e",
    user: { id: "3f2a1c9e", name: "Aline Mapendo", role: "SELLER", emails: [{ email: "aline@example.com", isPrimary: true, isVerified: true }] },
  },
};

export const KYC_GROUPS = ["Seller KYC"] as const;

export const kycEndpoints: EndpointDoc[] = [
  {
    slug: "submit-kyc",
    method: "POST",
    path: BASE,
    title: "Submit KYC",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Submits identity verification documents for the seller's profile — one submission per profile, ever. The seller's phone must already be verified and they must have at least one verified email.",
    bodyParams: [
      { name: "idDocumentType", type: "string", required: true, description: "NATIONAL_ID, VOTER_CARD, or PASSPORT." },
      { name: "idDocument", type: "file", required: true, description: "Image or PDF." },
      { name: "proofOfAddress", type: "file", required: true, description: "Image or PDF." },
      { name: "selfie", type: "file", required: true, description: "Image only — no PDF." },
      { name: "rccmNumber", type: "string", required: false, description: "Business registration number. Must be provided together with rccmDocument, or not at all." },
      { name: "rccmDocument", type: "file", required: false, description: "Image or PDF." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleKyc },
    errorExamples: [
      { status: 403, code: "FORBIDDEN", message: "Votre numéro de téléphone doit être vérifié avant de soumettre un dossier KYC." },
      { status: 409, code: "CONFLICT", message: "Un dossier KYC existe déjà pour ce profil vendeur. Utilisez la resoumission à la place." },
    ],
  },
  {
    slug: "get-my-kyc",
    method: "GET",
    path: `${BASE}/my-kyc`,
    title: "Get my KYC",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Returns the signed-in seller's own KYC record and its current status.",
    successStatus: 200,
    responseExample: { success: true, data: sampleKyc },
  },
  {
    slug: "resubmit-kyc",
    method: "POST",
    path: `${BASE}/resubmit`,
    title: "Resubmit KYC",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Replaces one or more documents on a rejected KYC record and resets it to PENDING. Only allowed while status is REJECTED — files omitted here keep their previously-submitted value.",
    bodyParams: [
      { name: "idDocumentType", type: "string", required: false, description: "NATIONAL_ID, VOTER_CARD, or PASSPORT." },
      { name: "idDocument", type: "file", required: false, description: "Image or PDF." },
      { name: "proofOfAddress", type: "file", required: false, description: "Image or PDF." },
      { name: "selfie", type: "file", required: false, description: "Image only." },
      { name: "rccmNumber", type: "string", required: false, description: "" },
      { name: "rccmDocument", type: "file", required: false, description: "Image or PDF." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleKyc, status: "PENDING" } },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: 'Ce dossier KYC ne peut pas être resoumis car son statut est "PENDING".' },
    ],
  },
  {
    slug: "list-kyc",
    method: "GET",
    path: BASE,
    title: "List KYC submissions",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists KYC submissions for review. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "PENDING, SUPPORT_REVIEWED, APPROVED, or REJECTED." },
      { name: "search", type: "string", required: false, description: "Matches the seller's business name." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { records: [sampleKycDetail], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "get-kyc-detail",
    method: "GET",
    path: `${BASE}/:id`,
    title: "Get KYC detail",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Returns full detail for one KYC submission, including the seller's profile and account info — sensitive fields (passwords, OTP/reset codes) are stripped. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "KYC record ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleKycDetail },
  },
  {
    slug: "support-review-kyc",
    method: "POST",
    path: `${BASE}/:id/support-review`,
    title: "Mark support-reviewed",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["SUPPORT", "ADMIN"],
    rateLimit: "Authenticated action",
    description: "The first review step, typically after a verification call with the seller. Moves the record to SUPPORT_REVIEWED and notifies admins it's ready for final approval.",
    pathParams: [{ name: "id", type: "string", required: true, description: "KYC record ID." }],
    bodyParams: [{ name: "callNotes", type: "string", required: true, description: "Notes from the verification call — required." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleKyc, status: "SUPPORT_REVIEWED" } },
  },
  {
    slug: "approve-kyc",
    method: "POST",
    path: `${BASE}/:id/approve`,
    title: "Approve KYC",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Final approval — activates the seller's profile in the same transaction. Admin-only; Support can review but not give final approval.",
    pathParams: [{ name: "id", type: "string", required: true, description: "KYC record ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleKyc, status: "APPROVED" } },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: 'Transition de statut KYC invalide : "PENDING" → "APPROVED".' },
    ],
    notes: ["A KYC record must be SUPPORT_REVIEWED before it can be approved — it can't go straight from PENDING to APPROVED."],
  },
  {
    slug: "reject-kyc",
    method: "POST",
    path: `${BASE}/:id/reject`,
    title: "Reject KYC",
    group: "Seller KYC",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Rejects a submission — the seller can resubmit afterward.",
    pathParams: [{ name: "id", type: "string", required: true, description: "KYC record ID." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "A clear reason — required, and shown to the seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleKyc, status: "REJECTED" } },
  },
];
