import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/notifications";

const sampleNotification = {
  id: "notif_1a2b3c",
  userId: "3f2a1c9e",
  type: "ORDER_STATUS",
  title: "Votre commande a été acceptée",
  body: "Boutique Aline vient d'accepter votre commande.",
  data: { orderId: "ord_5e6f7a" },
  isRead: false,
  createdAt: "2026-02-15T09:10:00.000Z",
};

const samplePreferences = {
  ORDER_STATUS: { inApp: true, email: true, sms: false, push: true },
  ORDER_MESSAGE: { inApp: true, email: false, sms: false, push: true },
  PAYMENT: { inApp: true, email: true, sms: false, push: true },
  ACCOUNT_SECURITY: { inApp: true, email: true, sms: true, push: true },
  PROMO: { inApp: true, email: false, sms: false, push: false },
  SELLER_ONBOARDING: { inApp: true, email: true, sms: false, push: true },
  SUPPORT: { inApp: true, email: true, sms: false, push: true },
  SYSTEM: { inApp: true, email: false, sms: false, push: true },
};

export const NOTIFICATION_GROUPS = ["Notifications"] as const;

export const notificationEndpoints: EndpointDoc[] = [
  {
    slug: "list-notifications",
    method: "GET",
    path: BASE,
    title: "List notifications",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists the signed-in user's notifications, most recent first.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "unreadOnly", type: "boolean", required: false, description: "Only return unread notifications." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { notifications: [sampleNotification], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
    notes: ["Notifications are retained for 90 days."],
  },
  {
    slug: "mark-notification-read",
    method: "POST",
    path: `${BASE}/:id/read`,
    title: "Mark notification read",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Marks a single notification as read.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Notification ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleNotification, isRead: true } },
  },
  {
    slug: "mark-all-notifications-read",
    method: "POST",
    path: `${BASE}/read-all`,
    title: "Mark all notifications read",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Marks every unread notification on the account as read.",
    successStatus: 200,
    responseExample: { success: true, data: { updatedCount: 4 } },
  },
  {
    slug: "delete-notification",
    method: "DELETE",
    path: `${BASE}/:id`,
    title: "Delete notification",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Removes a single notification.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Notification ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
  {
    slug: "get-notification-preferences",
    method: "GET",
    path: `${BASE}/preferences`,
    title: "Get notification preferences",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns which channels (in-app, email, SMS, push) are enabled per notification type.",
    successStatus: 200,
    responseExample: { success: true, data: samplePreferences },
  },
  {
    slug: "update-notification-preference",
    method: "PUT",
    path: `${BASE}/preferences`,
    title: "Update notification preference",
    group: "Notifications",
    auth: "bearer",
    rateLimit: "Session",
    description: "Updates channel settings for one notification type.",
    bodyParams: [
      { name: "type", type: "string", required: true, description: "ORDER_STATUS, ORDER_MESSAGE, PAYMENT, ACCOUNT_SECURITY, PROMO, SELLER_ONBOARDING, SUPPORT, or SYSTEM." },
      { name: "inApp", type: "boolean", required: false, description: "" },
      { name: "email", type: "boolean", required: false, description: "" },
      { name: "sms", type: "boolean", required: false, description: "" },
      { name: "push", type: "boolean", required: false, description: "" },
    ],
    successStatus: 200,
    responseExample: { success: true, data: samplePreferences.ORDER_STATUS },
    notes: ["ACCOUNT_SECURITY notifications can't be fully disabled — critical security alerts always deliver regardless of preference."],
  },
  {
    slug: "create-notification",
    method: "POST",
    path: BASE,
    title: "Create notification",
    group: "Notifications",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Sends a notification directly to a specific user. Staff-only — used for manual, one-off communication outside the platform's automated notification triggers.",
    bodyParams: [
      { name: "userId", type: "string", required: true, description: "Recipient's user ID." },
      { name: "type", type: "string", required: true, description: "One of the notification types." },
      { name: "title", type: "string", required: true, description: "" },
      { name: "body", type: "string", required: true, description: "" },
      { name: "data", type: "object", required: false, description: "Arbitrary metadata delivered alongside the notification." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleNotification },
  },
];
