import type { EndpointDoc } from "@/lib/types";

const CART_BASE = "/api/v1/cart";
const ORDER_BASE = "/api/v1/orders";
const ADMIN_BASE = "/api/v1/orders/admin";

const sampleCartItem = {
  id: "item_1a2b3c",
  variantId: "var_4d5e6f",
  productName: "Riz parfumé 25kg",
  quantity: 2,
  unitPrice: "12.50",
};

const sampleCart = {
  id: "cart_9f8e7d",
  shopId: "shop_2b3c4d",
  buyerId: "3f2a1c9e",
  currency: "USD",
  items: [sampleCartItem],
  subtotal: "25.00",
};

const sampleOrderItem = {
  id: "oitem_1a2b3c",
  productId: "prod_7c8d9e",
  variantId: "var_4d5e6f",
  name: "Riz parfumé 25kg",
  quantity: 2,
  unitPrice: "12.50",
  lineTotal: "25.00",
};

const sampleOrder = {
  id: "ord_5e6f7a",
  buyerId: "3f2a1c9e",
  shopId: "shop_2b3c4d",
  status: "PENDING_SELLER_REVIEW",
  fulfillmentMethod: "DELIVERY",
  paymentMethod: "MOBILE_MONEY",
  currency: "USD",
  deliveryAddress: "12 Avenue du Lac, Goma",
  deliveryFee: "2.00",
  subtotal: "25.00",
  total: "27.00",
  items: [sampleOrderItem],
  createdAt: "2026-02-15T09:00:00.000Z",
  updatedAt: "2026-02-15T09:00:00.000Z",
};

const sampleMessage = {
  id: "msg_1a2b3c",
  orderId: "ord_5e6f7a",
  senderId: "3f2a1c9e",
  body: "Je suis devant la porte bleue, merci.",
  isRead: false,
  createdAt: "2026-02-15T10:20:00.000Z",
};

export const ORDER_GROUPS = [
  "Cart",
  "Checkout & Orders",
  "Seller Fulfillment",
  "Rider Delivery",
  "Order Messages",
  "Order Moderation",
] as const;

export const orderEndpoints: EndpointDoc[] = [
  // --- Cart ---
  {
    slug: "add-cart-item",
    method: "POST",
    path: `${CART_BASE}/items`,
    title: "Add item to cart",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Adds a variant to the buyer's cart for a shop, creating the cart if one doesn't exist yet. Increments quantity if the variant is already in the cart.",
    bodyParams: [
      { name: "shopId", type: "string", required: true, description: "The shop this cart belongs to — a buyer has one cart per shop." },
      { name: "variantId", type: "string", required: true, description: "Must belong to a published product in that shop." },
      { name: "quantity", type: "number", required: true, description: "1–1000." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleCartItem },
    notes: ["A cart holds at most 50 line items."],
  },
  {
    slug: "update-cart-item",
    method: "PUT",
    path: `${CART_BASE}/items/:itemId`,
    title: "Update cart item quantity",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Sets a cart line item's quantity to an absolute value.",
    pathParams: [{ name: "itemId", type: "string", required: true, description: "Cart item ID." }],
    bodyParams: [{ name: "quantity", type: "number", required: true, description: "1–1000." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleCartItem, quantity: 3 } },
  },
  {
    slug: "remove-cart-item",
    method: "DELETE",
    path: `${CART_BASE}/items/:itemId`,
    title: "Remove cart item",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Removes a single line item from a cart.",
    pathParams: [{ name: "itemId", type: "string", required: true, description: "Cart item ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { removed: true } },
  },
  {
    slug: "list-my-carts",
    method: "GET",
    path: CART_BASE,
    title: "List my carts",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists every non-empty cart the buyer has — one per shop they've added items from.",
    successStatus: 200,
    responseExample: { success: true, data: [sampleCart] },
  },
  {
    slug: "get-cart-for-shop",
    method: "GET",
    path: `${CART_BASE}/shop/:shopId`,
    title: "Get cart for a shop",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns the buyer's cart for one shop, with line items priced in the shop's currency by default.",
    pathParams: [{ name: "shopId", type: "string", required: true, description: "Shop ID." }],
    queryParams: [
      { name: "currency", type: "string", required: false, description: "USD or CDF — converts displayed totals using the configured exchange rate." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleCart },
  },
  {
    slug: "clear-cart",
    method: "POST",
    path: `${CART_BASE}/shop/:shopId/clear`,
    title: "Clear cart",
    group: "Cart",
    auth: "bearer",
    rateLimit: "Session",
    description: "Empties the buyer's cart for one shop.",
    pathParams: [{ name: "shopId", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { cleared: true } },
  },
  // --- Checkout & Orders ---
  {
    slug: "checkout",
    method: "POST",
    path: `${ORDER_BASE}/checkout`,
    title: "Checkout",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Payment",
    description: "Converts a shop's cart into an order and initiates payment. Idempotent — retrying an identical checkout request with the same idempotency key returns the original order instead of creating a duplicate.",
    bodyParams: [
      { name: "shopId", type: "string", required: true, description: "The shop being checked out — its cart must have at least one item." },
      { name: "paymentMethod", type: "string", required: true, description: "e.g. MOBILE_MONEY." },
      { name: "fulfillmentMethod", type: "string", required: true, description: "DELIVERY or PICKUP." },
      { name: "deliveryAddress", type: "string", required: false, description: "10–300 characters. Required when fulfillmentMethod is DELIVERY." },
      { name: "deliveryLatitude", type: "number", required: false, description: "Required when fulfillmentMethod is DELIVERY." },
      { name: "deliveryLongitude", type: "number", required: false, description: "Required when fulfillmentMethod is DELIVERY." },
      { name: "payerPhoneNumber", type: "string", required: true, description: "Mobile money number to charge." },
      { name: "network", type: "string", required: true, description: "Mobile money provider." },
      { name: "countryCode", type: "string", required: true, description: "ISO country code." },
      { name: "currency", type: "string", required: true, description: "USD or CDF." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { ...sampleOrder, status: "AWAITING_PAYMENT" } },
    notes: [
      "The order starts as AWAITING_PAYMENT and moves to PENDING_SELLER_REVIEW automatically once the payment provider confirms the charge.",
      "Send an Idempotency-Key header to make retries safe.",
    ],
  },
  {
    slug: "list-my-orders",
    method: "GET",
    path: `${ORDER_BASE}/me`,
    title: "List my orders",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists the signed-in buyer's orders.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "Filter by order status." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { orders: [sampleOrder], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "get-order",
    method: "GET",
    path: `${ORDER_BASE}/:id`,
    title: "Get order",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns full order detail. Accessible to the buyer, the seller, and an assigned rider on that order.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleOrder },
  },
  {
    slug: "cancel-order",
    method: "POST",
    path: `${ORDER_BASE}/:id/cancel`,
    title: "Cancel order",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Cancels an order — buyer-initiated. Only allowed while the order is still in a cancellable state.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Shown to the seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "CANCELLED" } },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: 'Transition de statut invalide : "ON_THE_WAY" → "CANCELLED".' },
    ],
    notes: ["Cancellable from AWAITING_PAYMENT, PENDING_SELLER_REVIEW, ACCEPTED, PREPARING, READY_FOR_PICKUP, or RIDER_ASSIGNED — not once a rider has picked up the order."],
  },
  {
    slug: "confirm-receipt",
    method: "POST",
    path: `${ORDER_BASE}/:id/confirm-receipt`,
    title: "Confirm receipt",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Buyer confirms they've received the order, moving it from DELIVERED to COMPLETED. If the buyer never confirms, the order auto-completes 48 hours after delivery.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "COMPLETED" } },
  },
  {
    slug: "get-order-qr",
    method: "GET",
    path: `${ORDER_BASE}/:id/qr-code`,
    title: "Get order QR code",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Returns a single-use QR token for the order, used to confirm handoff at pickup or delivery.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { qrToken: "qr_8f1b2c3d4e5f6789" } },
  },
  {
    slug: "scan-order-qr",
    method: "POST",
    path: `${ORDER_BASE}/scan`,
    title: "Scan order QR code",
    group: "Checkout & Orders",
    auth: "bearer",
    rateLimit: "Session",
    description: "Resolves a scanned QR token to its order — the first step before completing a pickup or delivery handoff.",
    bodyParams: [{ name: "qrToken", type: "string", required: true, description: "Token from GET /:id/qr-code." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleOrder },
  },
  // --- Seller Fulfillment ---
  {
    slug: "accept-order",
    method: "POST",
    path: `${ORDER_BASE}/:id/accept`,
    title: "Accept order",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Accepts a new order into preparation. Must respond within the seller-review window, or the order expires automatically.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "ACCEPTED" } },
    notes: ["Sellers have 120 minutes to accept or reject a new order before it expires automatically."],
  },
  {
    slug: "reject-order",
    method: "POST",
    path: `${ORDER_BASE}/:id/reject`,
    title: "Reject order",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Declines a new order — the buyer is refunded in full.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Shown to the buyer." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "REJECTED" } },
  },
  {
    slug: "mark-order-ready",
    method: "POST",
    path: `${ORDER_BASE}/:id/ready`,
    title: "Mark order ready",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Marks a pickup order as ready for the buyer to collect.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, fulfillmentMethod: "PICKUP", status: "READY_FOR_PICKUP" } },
  },
  {
    slug: "complete-pickup",
    method: "POST",
    path: `${ORDER_BASE}/:id/complete-pickup`,
    title: "Complete pickup handoff",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Confirms the buyer picked up the order in person, by scanning their QR code.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [{ name: "qrToken", type: "string", required: true, description: "From the buyer's GET /:id/qr-code, resolved via POST /scan." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, fulfillmentMethod: "PICKUP", status: "COMPLETED" } },
  },
  {
    slug: "assign-rider",
    method: "POST",
    path: `${ORDER_BASE}/:id/assign-rider`,
    title: "Assign rider",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Assigns a delivery order to one of the seller's riders.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [{ name: "riderId", type: "string", required: true, description: "Must be one of the seller's own riders." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "RIDER_ASSIGNED" } },
  },
  {
    slug: "list-shop-orders",
    method: "GET",
    path: `${ORDER_BASE}/shop/:shopId`,
    title: "List shop orders",
    group: "Seller Fulfillment",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Lists orders for one of the seller's shops.",
    pathParams: [{ name: "shopId", type: "string", required: true, description: "Must belong to the authenticated seller." }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "Filter by order status." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { orders: [sampleOrder], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  // --- Rider Delivery ---
  {
    slug: "mark-picked-up",
    method: "POST",
    path: `${ORDER_BASE}/:id/picked-up`,
    title: "Mark picked up",
    group: "Rider Delivery",
    auth: "bearer",
    roles: ["RIDER"],
    rateLimit: "Session",
    description: "Rider confirms they've collected the order from the seller.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must be assigned to the authenticated rider." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "PICKED_UP" } },
  },
  {
    slug: "mark-on-the-way",
    method: "POST",
    path: `${ORDER_BASE}/:id/on-the-way`,
    title: "Mark on the way",
    group: "Rider Delivery",
    auth: "bearer",
    roles: ["RIDER"],
    rateLimit: "Session",
    description: "Rider marks the order as en route to the buyer. This is also when order messaging opens up.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must be assigned to the authenticated rider." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "ON_THE_WAY" } },
  },
  {
    slug: "complete-delivery",
    method: "POST",
    path: `${ORDER_BASE}/:id/complete-delivery`,
    title: "Complete delivery",
    group: "Rider Delivery",
    auth: "bearer",
    roles: ["RIDER"],
    rateLimit: "Session",
    description: "Confirms handoff to the buyer, by scanning their QR code.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must be assigned to the authenticated rider." }],
    bodyParams: [{ name: "qrToken", type: "string", required: true, description: "From the buyer's GET /:id/qr-code, resolved via POST /scan." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "DELIVERED" } },
  },
  {
    slug: "mark-failed-delivery",
    method: "POST",
    path: `${ORDER_BASE}/:id/failed-delivery`,
    title: "Mark failed delivery",
    group: "Rider Delivery",
    auth: "bearer",
    roles: ["RIDER"],
    rateLimit: "Session",
    description: "Reports that the delivery couldn't be completed — e.g. the buyer was unreachable.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must be assigned to the authenticated rider." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "Why the delivery failed." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "FAILED" } },
  },
  {
    slug: "list-my-deliveries",
    method: "GET",
    path: `${ORDER_BASE}/rider/me`,
    title: "List my deliveries",
    group: "Rider Delivery",
    auth: "bearer",
    roles: ["RIDER"],
    rateLimit: "Session",
    description: "Lists orders assigned to the signed-in rider.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "Filter by order status." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { orders: [sampleOrder], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  // --- Order Messages ---
  {
    slug: "list-order-messages",
    method: "GET",
    path: `${ORDER_BASE}/:id/messages`,
    title: "List order messages",
    group: "Order Messages",
    auth: "bearer",
    rateLimit: "Session",
    description: "Lists the chat thread between buyer and rider for a delivery in progress. Accessible to the buyer and the assigned rider.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: [sampleMessage] },
  },
  {
    slug: "send-order-message",
    method: "POST",
    path: `${ORDER_BASE}/:id/messages`,
    title: "Send order message",
    group: "Order Messages",
    auth: "bearer",
    rateLimit: "Chat message — 20 per minute",
    description: "Sends a message on the order's chat thread — only while the order is actively out for delivery.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    bodyParams: [{ name: "body", type: "string", required: true, description: "Up to 1000 characters." }],
    successStatus: 201,
    responseExample: { success: true, data: sampleMessage },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "La messagerie n'est disponible que pendant la livraison." },
    ],
    notes: ["Messaging is only open while the order is RIDER_ASSIGNED, PICKED_UP, or ON_THE_WAY."],
  },
  {
    slug: "mark-order-messages-read",
    method: "POST",
    path: `${ORDER_BASE}/:id/messages/read`,
    title: "Mark messages read",
    group: "Order Messages",
    auth: "bearer",
    rateLimit: "Session",
    description: "Marks every unread message on the order's thread as read for the caller.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { orderId: "ord_5e6f7a" } },
  },
  // --- Order Moderation ---
  {
    slug: "admin-list-orders",
    method: "GET",
    path: ADMIN_BASE,
    title: "List all orders",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Lists orders across the platform. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "Filter by order status." },
      { name: "shopId", type: "string", required: false, description: "Filter by shop." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { orders: [sampleOrder], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "admin-get-order",
    method: "GET",
    path: `${ADMIN_BASE}/:id`,
    title: "Get order detail",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT", "ACCOUNTANT"],
    rateLimit: "Session",
    description: "Returns full detail for any order on the platform. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleOrder },
  },
  {
    slug: "admin-cancel-order",
    method: "POST",
    path: `${ADMIN_BASE}/:id/cancel`,
    title: "Cancel order (staff)",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Cancels any order on the buyer's behalf, e.g. for a support case. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Internal note, also shown to buyer and seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleOrder, status: "CANCELLED" } },
  },
  {
    slug: "admin-request-order-refund-approval",
    method: "POST",
    path: `${ADMIN_BASE}/:id/refund/request-approval`,
    title: "Request order refund approval",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout OTP",
    description: "Starts the OTP-gated refund flow for an order — emails a verification code to the admin.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { pendingId: "9f8e7d6c-5b4a-3210-9f8e-7d6c5b4a3210", message: "Un code de vérification a été envoyé à admin@swiftgoma.com.", expiresInMinutes: 5 },
    },
  },
  {
    slug: "admin-confirm-order-refund",
    method: "POST",
    path: `${ADMIN_BASE}/:id/refund/confirm`,
    title: "Confirm order refund",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout confirm",
    description: "Completes the OTP-gated refund flow, issuing the refund.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    bodyParams: [
      { name: "pendingId", type: "string", required: true, description: "From POST /refund/request-approval." },
      { name: "code", type: "string", required: true, description: "The verification code from the email." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleOrder },
  },
  {
    slug: "admin-refund-order",
    method: "POST",
    path: `${ADMIN_BASE}/:id/refund`,
    title: "Refund order (direct)",
    group: "Order Moderation",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Payout confirm",
    description: "Issues a refund directly, without the OTP step.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Order ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleOrder },
  },
];
