import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/products";
const ADMIN_BASE = "/api/v1/products/admin";

const sampleCategory = {
  id: "cat_9f1e2a3b",
  name: "Alimentation & Boissons",
  slug: "alimentation-boissons",
  sortOrder: 0,
  isActive: true,
  subcategories: [
    { id: "sub_1a2b3c", categoryId: "cat_9f1e2a3b", name: "Boissons", slug: "boissons", sortOrder: 0, isActive: true },
  ],
};

const sampleVariant = {
  id: "var_4d5e6f",
  name: null,
  attributes: null,
  sku: null,
  price: "12.50",
  stock: 40,
  isDefault: true,
};

const sampleProduct = {
  id: "prod_7c8d9e",
  shopId: "shop_2b3c4d",
  subcategoryId: "sub_1a2b3c",
  name: "Riz parfumé 25kg",
  slug: "riz-parfume-25kg",
  description: "Riz parfumé de qualité supérieure, sac de 25kg, idéal pour la revente ou la consommation familiale.",
  brand: "Uncle Sam",
  unit: "piece",
  weightGrams: 25000,
  currency: "USD",
  status: "PUBLISHED",
  hasVariants: false,
  images: [
    { id: "img_1", url: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/products/riz-1.jpg", position: 0 },
  ],
  variants: [sampleVariant],
  createdAt: "2026-01-10T09:00:00.000Z",
  updatedAt: "2026-01-14T10:32:00.000Z",
};

const sampleProductDetail = {
  ...sampleProduct,
  subcategory: sampleCategory.subcategories[0],
  shop: { id: "shop_2b3c4d", name: "Boutique Aline", slug: "boutique-aline", status: "PUBLISHED", logoUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/shops/aline-logo.jpg", sellerProfile: { city: "Goma" } },
  rating: { average: 4.5, count: 12 },
  reviews: [
    { id: "rev_1", authorName: "Aline Mapendo", rating: 5, comment: "Excellent produit, livraison rapide.", createdAt: "2026-01-20T12:00:00.000Z" },
  ],
  purchaseCount: 34,
};

const sampleExchangeRate = {
  id: "fx_1a2b3c",
  fromCurrency: "USD",
  toCurrency: "CDF",
  rate: "2800",
  updatedBy: "admin_9f8e7d",
  updatedAt: "2026-02-01T08:00:00.000Z",
};

const sampleStockMovement = {
  id: "mv_1a2b3c",
  variantId: "var_4d5e6f",
  type: "RESTOCK",
  amount: 20,
  reason: "Réapprovisionnement fournisseur",
  stockBefore: 20,
  stockAfter: 40,
  createdAt: "2026-02-10T14:00:00.000Z",
};

export const PRODUCT_GROUPS = [
  "Categories",
  "Products",
  "Reviews",
  "Stock",
  "Exchange Rates",
  "Moderation",
] as const;

export const productEndpoints: EndpointDoc[] = [
  // --- Categories ---
  {
    slug: "list-categories",
    method: "GET",
    path: `${BASE}/categories`,
    title: "List categories",
    group: "Categories",
    auth: "none",
    rateLimit: "Public",
    description: "Lists categories with their subcategories, ordered for display. Cached for 10 minutes.",
    queryParams: [
      { name: "includeInactive", type: "boolean", required: false, description: "Include disabled categories/subcategories. Defaults to false." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: [sampleCategory] },
  },
  {
    slug: "get-category",
    method: "GET",
    path: `${BASE}/categories/:id`,
    title: "Get category",
    group: "Categories",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a single category with its subcategories.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Category ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleCategory },
  },
  {
    slug: "create-category",
    method: "POST",
    path: `${BASE}/categories`,
    title: "Create category",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Creates a top-level category. Staff-only.",
    bodyParams: [
      { name: "name", type: "string", required: true, description: "2–60 characters, unique." },
      { name: "sortOrder", type: "number", required: false, description: "Display order, ascending. Defaults to 0." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { ...sampleCategory, subcategories: [] } },
  },
  {
    slug: "update-category",
    method: "PUT",
    path: `${BASE}/categories/:id`,
    title: "Update category",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Updates a category's name, sort order, or active state. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Category ID." }],
    bodyParams: [
      { name: "name", type: "string", required: false, description: "2–60 characters." },
      { name: "sortOrder", type: "number", required: false, description: "Display order." },
      { name: "isActive", type: "boolean", required: false, description: "Inactive categories are hidden from public listings." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleCategory },
  },
  {
    slug: "delete-category",
    method: "DELETE",
    path: `${BASE}/categories/:id`,
    title: "Delete category",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Deletes a category. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Category ID." }],
    successStatus: 200,
    responseExample: { success: true, message: "Catégorie supprimée." },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Impossible de supprimer cette catégorie : elle contient encore des sous-catégories." },
    ],
  },
  {
    slug: "create-subcategory",
    method: "POST",
    path: `${BASE}/categories/:categoryId/subcategories`,
    title: "Create subcategory",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Creates a subcategory under a parent category. Staff-only.",
    pathParams: [{ name: "categoryId", type: "string", required: true, description: "Parent category ID." }],
    bodyParams: [
      { name: "name", type: "string", required: true, description: "2–60 characters, unique within the parent category." },
      { name: "sortOrder", type: "number", required: false, description: "Display order. Defaults to 0." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleCategory.subcategories[0] },
  },
  {
    slug: "update-subcategory",
    method: "PUT",
    path: `${BASE}/categories/subcategories/:id`,
    title: "Update subcategory",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Updates a subcategory's name, sort order, or active state. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Subcategory ID." }],
    bodyParams: [
      { name: "name", type: "string", required: false, description: "2–60 characters." },
      { name: "sortOrder", type: "number", required: false, description: "Display order." },
      { name: "isActive", type: "boolean", required: false, description: "Inactive subcategories are hidden from public listings." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleCategory.subcategories[0] },
  },
  {
    slug: "delete-subcategory",
    method: "DELETE",
    path: `${BASE}/categories/subcategories/:id`,
    title: "Delete subcategory",
    group: "Categories",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Deletes a subcategory. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Subcategory ID." }],
    successStatus: 200,
    responseExample: { success: true, message: "Sous-catégorie supprimée." },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Impossible de supprimer cette sous-catégorie : des produits y sont encore rattachés." },
    ],
  },
  // --- Products ---
  {
    slug: "list-products",
    method: "GET",
    path: BASE,
    title: "List products",
    group: "Products",
    auth: "none",
    rateLimit: "Public",
    description: "Lists published products from published shops, with filtering, search, and sorting. Cached for 2 minutes per filter combination.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "categoryId", type: "string", required: false, description: "Filter by category." },
      { name: "subcategoryId", type: "string", required: false, description: "Filter by subcategory." },
      { name: "shopId", type: "string", required: false, description: "Filter by shop." },
      { name: "minPrice", type: "number", required: false, description: "Minimum variant price." },
      { name: "maxPrice", type: "number", required: false, description: "Maximum variant price." },
      { name: "currency", type: "string", required: false, description: "USD or CDF." },
      { name: "search", type: "string", required: false, description: "Matches name, description, and brand." },
      { name: "inStockOnly", type: "boolean", required: false, description: "Only products with at least one in-stock variant." },
      { name: "city", type: "string", required: false, description: "Filter by seller's city." },
      { name: "sortBy", type: "string", required: false, description: "recent (default), popular, priceAsc, or priceDesc." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        products: [sampleProduct],
        pagination: { page: 1, limit: 20, total: 1, totalPages: 1 },
      },
    },
  },
  {
    slug: "list-popular-products",
    method: "GET",
    path: `${BASE}/popular`,
    title: "List popular products",
    group: "Products",
    auth: "none",
    rateLimit: "Public",
    description: "Shortcut for GET / with sortBy=popular — ranked by a rolling 30-day score of sales, favorites, views, and reviews.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "categoryId", type: "string", required: false, description: "Filter by category." },
      { name: "shopId", type: "string", required: false, description: "Filter by shop." },
      { name: "currency", type: "string", required: false, description: "USD or CDF." },
      { name: "city", type: "string", required: false, description: "Filter by seller's city." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { products: [sampleProduct], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "get-product-by-slug",
    method: "GET",
    path: `${BASE}/slug/:slug`,
    title: "Get product",
    group: "Products",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a published product's full detail, including its rating summary, recent reviews, and purchase count. Records a view for popularity ranking.",
    pathParams: [{ name: "slug", type: "string", required: true, description: "Product slug." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleProductDetail },
    errorExamples: [{ status: 404, code: "NOT_FOUND", message: "Produit introuvable." }],
  },
  {
    slug: "create-product",
    method: "POST",
    path: BASE,
    title: "Create product",
    group: "Products",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Creates a product as a draft in one of the seller's own shops. Requires an active subscription with enough remaining product and photo quota.",
    bodyParams: [
      { name: "shopId", type: "string", required: true, description: "Must belong to the authenticated seller." },
      { name: "subcategoryId", type: "string", required: true, description: "Subcategory the product belongs to." },
      { name: "name", type: "string", required: true, description: "2–100 characters." },
      { name: "description", type: "string", required: true, description: "20–1000 characters." },
      { name: "brand", type: "string", required: false, description: "" },
      { name: "unit", type: "string", required: false, description: "piece, kg, liter, or pack. Defaults to piece." },
      { name: "weightGrams", type: "number", required: false, description: "1–500000." },
      { name: "expiresAt", type: "string", required: false, description: "ISO date. Required, and must be in the future, for food & beverage products." },
      { name: "currency", type: "string", required: true, description: "USD or CDF." },
      { name: "variants", type: "string", required: true, description: "JSON array of { name?, sku?, price, stock, attributes? }. At least one, max 50." },
      { name: "images", type: "file", required: false, description: "Up to 10 image files." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleProduct },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Votre plan (Starter) autorise au maximum 20 produit(s). Passez à un plan supérieur pour en ajouter davantage." },
    ],
    notes: ["New products are created with status DRAFT — publish them with POST /:id/status."],
  },
  {
    slug: "list-shop-products",
    method: "GET",
    path: `${BASE}/shop/:shopId`,
    title: "List a shop's products",
    group: "Products",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Lists every product — any status — in one of the seller's own shops.",
    pathParams: [{ name: "shopId", type: "string", required: true, description: "Must belong to the authenticated seller." }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "DRAFT, PUBLISHED, or ARCHIVED." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { products: [sampleProduct], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "update-product",
    method: "PUT",
    path: `${BASE}/:id`,
    title: "Update product",
    group: "Products",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Updates a product's descriptive fields. Doesn't touch images, variants, or status — use the dedicated endpoints for those.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [
      { name: "name", type: "string", required: false, description: "2–100 characters." },
      { name: "description", type: "string", required: false, description: "20–1000 characters." },
      { name: "brand", type: "string", required: false, description: "" },
      { name: "unit", type: "string", required: false, description: "piece, kg, liter, or pack." },
      { name: "weightGrams", type: "number", required: false, description: "1–500000." },
      { name: "expiresAt", type: "string", required: false, description: "ISO date. Re-validated against the food & beverage expiry rule when present." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleProduct },
  },
  {
    slug: "set-product-status",
    method: "POST",
    path: `${BASE}/:id/status`,
    title: "Change product status",
    group: "Products",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Publishes, archives, or drafts a product.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [{ name: "status", type: "string", required: true, description: "DRAFT, PUBLISHED, or ARCHIVED." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleProduct, status: "PUBLISHED" } },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: 'Transition de statut produit invalide : "ARCHIVED" → "PUBLISHED".' },
    ],
    notes: ["Valid transitions: DRAFT → PUBLISHED, PUBLISHED → ARCHIVED or DRAFT, ARCHIVED → DRAFT."],
  },
  // --- Reviews ---
  {
    slug: "submit-review",
    method: "POST",
    path: `${BASE}/:productId/reviews`,
    title: "Submit a review",
    group: "Reviews",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Leaves or updates a rating and comment on a product. Only buyers who have received the product (order status DELIVERED or COMPLETED) can review it — one review per product per buyer.",
    pathParams: [{ name: "productId", type: "string", required: true, description: "Product ID." }],
    bodyParams: [
      { name: "rating", type: "number", required: true, description: "Integer, 1–5." },
      { name: "comment", type: "string", required: true, description: "Up to 1000 characters." },
    ],
    successStatus: 201,
    responseExample: {
      success: true,
      data: { id: "rev_1", productId: "prod_7c8d9e", userId: "3f2a1c9e", rating: 5, comment: "Excellent produit, livraison rapide.", createdAt: "2026-02-15T10:00:00.000Z" },
    },
    errorExamples: [
      { status: 403, code: "FORBIDDEN", message: "Vous devez avoir reçu ce produit pour laisser un avis." },
    ],
    notes: ["Submitting again for the same product replaces the previous review instead of creating a second one."],
  },
  // --- Stock ---
  {
    slug: "adjust-stock",
    method: "POST",
    path: `${BASE}/variants/:variantId/stock`,
    title: "Adjust stock",
    group: "Stock",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Applies a signed stock adjustment to a variant — positive to restock, negative to remove stock. Fails atomically if it would take stock below zero.",
    pathParams: [{ name: "variantId", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    bodyParams: [
      { name: "type", type: "string", required: true, description: "e.g. RESTOCK, ADJUSTMENT, DAMAGE — a free-form label recorded on the movement." },
      { name: "amount", type: "number", required: true, description: "Signed integer. Positive adds stock, negative removes it." },
      { name: "reason", type: "string", required: false, description: "Free-text note." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleVariant, stock: 60 } },
    errorExamples: [{ status: 409, code: "CONFLICT", message: "Le stock ne peut pas être négatif." }],
  },
  {
    slug: "stock-history",
    method: "GET",
    path: `${BASE}/variants/:variantId/stock/history`,
    title: "Get stock history",
    group: "Stock",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Lists every stock movement recorded for a variant, most recent first.",
    pathParams: [{ name: "variantId", type: "string", required: true, description: "Must belong to one of the seller's shops." }],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { movements: [sampleStockMovement], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  // --- Exchange Rates ---
  {
    slug: "list-exchange-rates",
    method: "GET",
    path: `${BASE}/exchange-rates`,
    title: "List exchange rates",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists every configured currency pair. Staff-only.",
    successStatus: 200,
    responseExample: { success: true, data: [sampleExchangeRate] },
  },
  {
    slug: "get-exchange-rate",
    method: "GET",
    path: `${BASE}/exchange-rates/:id`,
    title: "Get exchange rate",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Returns one exchange rate pair. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Exchange rate ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleExchangeRate },
  },
  {
    slug: "create-exchange-rate",
    method: "POST",
    path: `${BASE}/exchange-rates`,
    title: "Create exchange rate",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Creates a rate for a currency pair that doesn't have one yet in either direction. Staff-only.",
    bodyParams: [
      { name: "fromCurrency", type: "string", required: true, description: "e.g. USD." },
      { name: "toCurrency", type: "string", required: true, description: "e.g. CDF." },
      { name: "rate", type: "number", required: true, description: "Must be greater than 0." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleExchangeRate },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Un taux existe déjà entre USD et CDF (USD → CDF). Utilisez la mise à jour à la place." },
    ],
  },
  {
    slug: "update-exchange-rate",
    method: "PUT",
    path: `${BASE}/exchange-rates/:id`,
    title: "Update exchange rate",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Updates the rate value for an existing pair. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Exchange rate ID." }],
    bodyParams: [{ name: "rate", type: "number", required: true, description: "Must be greater than 0." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleExchangeRate },
  },
  {
    slug: "upsert-exchange-rate",
    method: "PUT",
    path: `${BASE}/exchange-rates`,
    title: "Upsert exchange rate",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Creates the pair if it doesn't exist, or updates it if it does — in either direction. Staff-only.",
    bodyParams: [
      { name: "fromCurrency", type: "string", required: true, description: "e.g. USD." },
      { name: "toCurrency", type: "string", required: true, description: "e.g. CDF." },
      { name: "rate", type: "number", required: true, description: "Must be greater than 0." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleExchangeRate },
    notes: ["If the existing pair is stored in the opposite direction, the rate is automatically inverted before saving."],
  },
  {
    slug: "delete-exchange-rate",
    method: "DELETE",
    path: `${BASE}/exchange-rates/:id`,
    title: "Delete exchange rate",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Deletes an exchange rate pair. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Exchange rate ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { id: "fx_1a2b3c", deleted: true } },
  },
  {
    slug: "preview-conversion",
    method: "POST",
    path: `${BASE}/exchange-rates/preview`,
    title: "Preview a conversion",
    group: "Exchange Rates",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Converts an amount between two currencies using the configured rate, without saving anything. Staff-only.",
    bodyParams: [
      { name: "amount", type: "number", required: true, description: "Must be greater than or equal to 0." },
      { name: "fromCurrency", type: "string", required: true, description: "e.g. USD." },
      { name: "toCurrency", type: "string", required: true, description: "e.g. CDF." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { amount: 10, fromCurrency: "USD", toCurrency: "CDF", rate: 2800, convertedAmount: 28000 },
    },
  },
  // --- Admin ---
  {
    slug: "admin-list-products",
    method: "GET",
    path: ADMIN_BASE,
    title: "List all products",
    group: "Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists products across every shop on the platform, for moderation. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "status", type: "string", required: false, description: "DRAFT, PUBLISHED, or ARCHIVED." },
      { name: "shopId", type: "string", required: false, description: "Filter by shop." },
      { name: "search", type: "string", required: false, description: "Matches product name, slug, description, and shop name." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        items: [{ id: "prod_7c8d9e", name: "Riz parfumé 25kg", slug: "riz-parfume-25kg", status: "PUBLISHED", currency: "USD", minPrice: 12.5, variantCount: 1, shop: { id: "shop_2b3c4d", name: "Boutique Aline" } }],
        total: 1,
        page: 1,
        limit: 20,
        totalPages: 1,
      },
    },
  },
  {
    slug: "admin-get-product",
    method: "GET",
    path: `${ADMIN_BASE}/:id`,
    title: "Get product detail",
    group: "Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Returns full detail for one product, regardless of its status or shop. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Product ID." }],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { id: "prod_7c8d9e", name: "Riz parfumé 25kg", slug: "riz-parfume-25kg", status: "PUBLISHED", currency: "USD", minPrice: 12.5, variantCount: 1, shop: { id: "shop_2b3c4d", name: "Boutique Aline", status: "PUBLISHED" } },
    },
  },
  {
    slug: "admin-set-product-status",
    method: "POST",
    path: `${ADMIN_BASE}/:id/status`,
    title: "Moderate product status",
    group: "Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Takes a product down or drafts it, for policy violations or quality issues. Staff-only — deliberately can't publish a product on a seller's behalf.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Product ID." }],
    bodyParams: [
      { name: "status", type: "string", required: true, description: "DRAFT or ARCHIVED only." },
      { name: "reason", type: "string", required: false, description: "Shown to the seller in their moderation notification." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { id: "prod_7c8d9e", name: "Riz parfumé 25kg", status: "ARCHIVED" } },
    errorExamples: [
      { status: 400, code: "BAD_REQUEST", message: "Seuls les statuts DRAFT et ARCHIVED sont autorisés pour la modération admin." },
    ],
  },
];
