import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/seller";

const sampleSellerProfile = {
  id: "sp_2b3c4d",
  userId: "3f2a1c9e",
  businessName: "Boutique Aline",
  businessDescription: "Vente de produits alimentaires et de boissons en gros et au détail à Goma.",
  logoUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/sellers/aline-logo.jpg",
  bannerUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/sellers/aline-banner.jpg",
  contactPhone: "243812345678",
  contactEmail: "boutique.aline@example.com",
  whatsappNumber: "243812345678",
  address: "12 Avenue du Lac",
  city: "Goma",
  status: "ACTIVE",
  createdAt: "2026-01-05T08:00:00.000Z",
};

const sampleSellerProfileDetail = {
  ...sampleSellerProfile,
  kyc: { id: "kyc_8f1e2a", status: "APPROVED" },
  subscription: { id: "sub_9c8d7e", planId: "plan_starter", status: "ACTIVE" },
  walletSettings: { payoutPhoneNumber: "243812345678", provider: "MTN_MOMO_COD" },
  shops: [{ id: "shop_2b3c4d", name: "Boutique Aline", slug: "boutique-aline", status: "PUBLISHED" }],
  invoices: [],
};

export const SELLER_PROFILE_GROUPS = ["Seller Profile"] as const;

export const sellerProfileEndpoints: EndpointDoc[] = [
  {
    slug: "create-seller-profile",
    method: "POST",
    path: BASE,
    title: "Create seller profile",
    group: "Seller Profile",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Creates the seller profile for the signed-in account — the first step of onboarding. Created with status DRAFT; becomes ACTIVE automatically once KYC is approved.",
    bodyParams: [
      { name: "businessName", type: "string", required: true, description: "2–80 characters." },
      { name: "businessDescription", type: "string", required: true, description: "20–500 characters." },
      { name: "contactPhone", type: "string", required: true, description: "" },
      { name: "contactEmail", type: "string", required: true, description: "" },
      { name: "whatsappNumber", type: "string", required: true, description: "" },
      { name: "address", type: "string", required: true, description: "5–200 characters, no line breaks." },
      { name: "city", type: "string", required: true, description: "Currently only Goma is supported." },
      { name: "logo", type: "file", required: true, description: "Image file." },
      { name: "banner", type: "file", required: true, description: "Image file." },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleSellerProfile },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Un profil vendeur existe déjà pour ce compte." },
    ],
    notes: ["One seller profile per account — this fails if one already exists, even if it was later suspended."],
  },
  {
    slug: "get-my-seller-profile",
    method: "GET",
    path: `${BASE}/my-profile`,
    title: "Get my seller profile",
    group: "Seller Profile",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Returns the signed-in seller's profile, including their KYC status, subscription, wallet settings, shops, and recent invoices.",
    successStatus: 200,
    responseExample: { success: true, data: sampleSellerProfileDetail },
  },
  {
    slug: "update-seller-profile",
    method: "PUT",
    path: BASE,
    title: "Update seller profile",
    group: "Seller Profile",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Updates the signed-in seller's profile fields, logo, and/or banner. Only allowed while the profile is DRAFT or ACTIVE — not while SUSPENDED.",
    bodyParams: [
      { name: "businessName", type: "string", required: false, description: "2–80 characters." },
      { name: "businessDescription", type: "string", required: false, description: "20–500 characters." },
      { name: "contactPhone", type: "string", required: false, description: "" },
      { name: "contactEmail", type: "string", required: false, description: "" },
      { name: "whatsappNumber", type: "string", required: false, description: "" },
      { name: "address", type: "string", required: false, description: "5–200 characters, no line breaks." },
      { name: "city", type: "string", required: false, description: "Currently only Goma is supported." },
      { name: "logo", type: "file", required: false, description: "Replaces the existing logo." },
      { name: "banner", type: "file", required: false, description: "Replaces the existing banner." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleSellerProfile },
    errorExamples: [
      { status: 403, code: "FORBIDDEN", message: 'Ce profil ne peut pas être modifié car son statut est "SUSPENDED".' },
    ],
  },
  {
    slug: "suspend-seller-profile",
    method: "POST",
    path: `${BASE}/:userId/suspend`,
    title: "Suspend seller profile",
    group: "Seller Profile",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Suspends a seller's account entirely — blocks product management and hides their shops from buyers. Staff-only.",
    pathParams: [{ name: "userId", type: "string", required: true, description: "User ID of the seller." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "Shown to the seller in their suspension notification." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleSellerProfile, status: "SUSPENDED" } },
  },
  {
    slug: "reactivate-seller-profile",
    method: "POST",
    path: `${BASE}/:userId/reactivate`,
    title: "Reactivate seller profile",
    group: "Seller Profile",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Lifts a suspension, restoring the seller's account to ACTIVE. Staff-only.",
    pathParams: [{ name: "userId", type: "string", required: true, description: "User ID of the seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleSellerProfile, status: "ACTIVE" } },
  },
];
