import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/seller";

const sampleShop = {
  id: "shop_2b3c4d",
  sellerProfileId: "sp_2b3c4d",
  name: "Boutique Aline",
  slug: "boutique-aline",
  description: "Produits alimentaires et boissons en gros et au détail.",
  logoUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/shops/aline-logo.jpg",
  bannerUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/shops/aline-banner.jpg",
  deliveryFee: "2.00",
  deliveryFeeCurrency: "USD",
  status: "PUBLISHED",
  createdAt: "2026-01-08T09:00:00.000Z",
};

export const SHOP_GROUPS = ["Shops", "Shop Moderation"] as const;

export const shopEndpoints: EndpointDoc[] = [
  // --- Shops ---
  {
    slug: "get-shop-by-slug",
    method: "GET",
    path: `${BASE}/shop/slug/:slug`,
    title: "Get shop",
    group: "Shops",
    auth: "none",
    rateLimit: "Public",
    description: "Returns a published shop's public detail.",
    pathParams: [{ name: "slug", type: "string", required: true, description: "Shop slug." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleShop },
  },
  {
    slug: "list-shops",
    method: "GET",
    path: `${BASE}/shops`,
    title: "List shops",
    group: "Shops",
    auth: "none",
    rateLimit: "Public",
    description: "Lists published shops.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "search", type: "string", required: false, description: "Matches shop name." },
      { name: "city", type: "string", required: false, description: "Filter by city." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { shops: [sampleShop], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "create-shop",
    method: "POST",
    path: `${BASE}/shop`,
    title: "Create shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Creates a shop under the seller's profile. A seller can own multiple shops, up to their plan's shop limit.",
    bodyParams: [
      { name: "name", type: "string", required: true, description: "" },
      { name: "description", type: "string", required: true, description: "" },
      { name: "deliveryFee", type: "number", required: true, description: "" },
      { name: "deliveryFeeCurrency", type: "string", required: true, description: "USD or CDF." },
      { name: "logo", type: "file", required: true, description: "" },
      { name: "banner", type: "file", required: true, description: "" },
    ],
    successStatus: 201,
    responseExample: { success: true, data: { ...sampleShop, status: "DRAFT" } },
  },
  {
    slug: "list-my-shops",
    method: "GET",
    path: `${BASE}/shop/me`,
    title: "List my shops",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Session",
    description: "Lists every shop owned by the signed-in seller, any status.",
    successStatus: 200,
    responseExample: { success: true, data: [sampleShop] },
  },
  {
    slug: "update-shop",
    method: "PUT",
    path: `${BASE}/shop/:id`,
    title: "Update shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Updates one of the seller's own shops.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    bodyParams: [
      { name: "name", type: "string", required: false, description: "" },
      { name: "description", type: "string", required: false, description: "" },
      { name: "deliveryFee", type: "number", required: false, description: "" },
      { name: "deliveryFeeCurrency", type: "string", required: false, description: "" },
      { name: "logo", type: "file", required: false, description: "" },
      { name: "banner", type: "file", required: false, description: "" },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleShop },
  },
  {
    slug: "publish-shop",
    method: "POST",
    path: `${BASE}/shop/:id/publish`,
    title: "Publish shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Makes a shop visible to buyers.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "PUBLISHED" } },
  },
  {
    slug: "unpublish-shop",
    method: "POST",
    path: `${BASE}/shop/:id/unpublish`,
    title: "Unpublish shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Takes a shop back to draft, hiding it from buyers.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "DRAFT" } },
  },
  {
    slug: "suspend-my-shop",
    method: "POST",
    path: `${BASE}/shop/:id/suspend`,
    title: "Suspend my shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Seller-initiated pause — e.g. going on holiday — without deleting the shop.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "SUSPENDED" } },
  },
  {
    slug: "reactivate-my-shop",
    method: "POST",
    path: `${BASE}/shop/:id/reactivate`,
    title: "Reactivate my shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Reverses a self-suspension.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "PUBLISHED" } },
  },
  {
    slug: "delete-my-shop",
    method: "DELETE",
    path: `${BASE}/shop/:id`,
    title: "Delete my shop",
    group: "Shops",
    auth: "bearer",
    roles: ["SELLER"],
    rateLimit: "Authenticated action",
    description: "Deletes one of the seller's own shops. Only allowed while DRAFT or SUSPENDED — a PUBLISHED shop must be unpublished or suspended first.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
  // --- Shop Moderation ---
  {
    slug: "admin-list-shops",
    method: "GET",
    path: `${BASE}/shops/admin`,
    title: "List all shops",
    group: "Shop Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists every shop on the platform, any status. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Max 100. Defaults to 20." },
      { name: "search", type: "string", required: false, description: "Matches shop name." },
      { name: "status", type: "string", required: false, description: "DRAFT, PUBLISHED, or SUSPENDED." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { shops: [sampleShop], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } },
    },
  },
  {
    slug: "admin-suspend-shop",
    method: "POST",
    path: `${BASE}/shop/:id/admin/suspend`,
    title: "Suspend shop",
    group: "Shop Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Suspends a single shop — narrower than suspending the whole seller profile. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "Shown to the seller." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "SUSPENDED" } },
  },
  {
    slug: "admin-reactivate-shop",
    method: "POST",
    path: `${BASE}/shop/:id/admin/reactivate`,
    title: "Reactivate shop",
    group: "Shop Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Lifts a staff-issued shop suspension. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleShop, status: "PUBLISHED" } },
  },
  {
    slug: "admin-delete-shop",
    method: "DELETE",
    path: `${BASE}/shop/:id/admin`,
    title: "Delete shop",
    group: "Shop Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Deletes a shop on the platform's behalf. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Internal note." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
  {
    slug: "admin-restore-shop",
    method: "POST",
    path: `${BASE}/shop/:id/restore`,
    title: "Restore shop",
    group: "Shop Moderation",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Reverses an admin-initiated deletion. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Shop ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleShop },
  },
];
