import type { EndpointDoc } from "@/lib/types";

const PUBLIC_BASE = "/api/v1/storefront";
const ADMIN_BASE = "/api/v1/storefront/admin/hero-slides";

const sampleSlide = {
  id: "slide_1a2b3c",
  title: "Soldes de rentrée",
  subtitle: "Jusqu'à -30% sur une sélection de produits",
  imageUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/storefront/hero1.jpg",
  linkUrl: "/products?category=electronics",
  position: 1,
  isActive: true,
  createdAt: "2026-01-10T08:00:00.000Z",
};

export const STOREFRONT_GROUPS = ["Storefront"] as const;

export const storefrontEndpoints: EndpointDoc[] = [
  {
    slug: "get-hero-slides",
    method: "GET",
    path: `${PUBLIC_BASE}/hero`,
    title: "Get hero slides",
    group: "Storefront",
    auth: "none",
    rateLimit: "Public",
    description: "Returns the active hero carousel slides shown on the storefront home page, ordered by position.",
    successStatus: 200,
    responseExample: { success: true, data: [sampleSlide] },
  },
  {
    slug: "admin-list-hero-slides",
    method: "GET",
    path: ADMIN_BASE,
    title: "List hero slides",
    group: "Storefront",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Session",
    description: "Lists every hero slide, including inactive ones. Admin-only.",
    successStatus: 200,
    responseExample: { success: true, data: [sampleSlide] },
  },
  {
    slug: "admin-create-hero-slide",
    method: "POST",
    path: ADMIN_BASE,
    title: "Create hero slide",
    group: "Storefront",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Creates a new hero slide. Admin-only.",
    bodyParams: [
      { name: "title", type: "string", required: true, description: "" },
      { name: "subtitle", type: "string", required: false, description: "" },
      { name: "linkUrl", type: "string", required: false, description: "Where the slide links to when clicked." },
      { name: "position", type: "number", required: false, description: "Sort order. Lower numbers show first." },
      { name: "isActive", type: "boolean", required: false, description: "Defaults to true." },
      { name: "image", type: "file", required: true, description: "" },
    ],
    successStatus: 201,
    responseExample: { success: true, data: sampleSlide },
  },
  {
    slug: "admin-update-hero-slide",
    method: "PUT",
    path: `${ADMIN_BASE}/:id`,
    title: "Update hero slide",
    group: "Storefront",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Updates a hero slide's content, ordering, or image. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Hero slide ID." }],
    bodyParams: [
      { name: "title", type: "string", required: false, description: "" },
      { name: "subtitle", type: "string", required: false, description: "" },
      { name: "linkUrl", type: "string", required: false, description: "" },
      { name: "position", type: "number", required: false, description: "" },
      { name: "isActive", type: "boolean", required: false, description: "" },
      { name: "image", type: "file", required: false, description: "Replaces the existing image." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleSlide },
  },
  {
    slug: "admin-delete-hero-slide",
    method: "DELETE",
    path: `${ADMIN_BASE}/:id`,
    title: "Delete hero slide",
    group: "Storefront",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Deletes a hero slide. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "Hero slide ID." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
];
