import type { EndpointDoc } from "@/lib/types";

const BASE = "/api/v1/users";

const sampleUser = {
  id: "3f2a1c9e-7b41-4e2a-9c31-8e6b2d4f10aa",
  name: "Aline Mapendo",
  role: "BUYER",
  email: "aline@example.com",
  isEmailVerified: true,
  phone: "243812345678",
  isPhoneVerified: true,
  preferredCurrency: "USD",
  avatarUrl: "https://res.cloudinary.com/dx3wclabo/image/upload/v1/avatars/aline.jpg",
  isBlocked: false,
  createdAt: "2026-01-14T10:32:00.000Z",
};

export const USER_GROUPS = [
  "Profile",
  "Account Recovery",
  "Phone Number",
  "Secondary Email",
  "Google Account",
  "Admin",
] as const;

export const userEndpoints: EndpointDoc[] = [
  // --- Profile ---
  {
    slug: "update-profile",
    method: "PATCH",
    path: `${BASE}/profile`,
    title: "Update profile",
    group: "Profile",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Updates the signed-in user's display name and/or preferred display currency.",
    bodyParams: [
      { name: "name", type: "string", required: false, description: "New display name." },
      { name: "preferredCurrency", type: "string", required: false, description: "USD or CDF — used to format prices shown to this user." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "upload-avatar",
    method: "POST",
    path: `${BASE}/profile/avatar`,
    title: "Upload profile picture",
    group: "Profile",
    auth: "bearer",
    rateLimit: "Authenticated action",
    contentType: "multipart/form-data",
    description: "Uploads and sets a new profile picture, replacing the previous one.",
    bodyParams: [
      { name: "avatar", type: "file", required: true, description: "Image file (JPEG, PNG, or WEBP)." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
    errorExamples: [
      { status: 422, code: "VALIDATION_ERROR", message: "Aucun fichier image fourni." },
    ],
  },
  {
    slug: "delete-account",
    method: "POST",
    path: `${BASE}/delete`,
    title: "Delete account",
    group: "Profile",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Deletes the signed-in user's own account. If the account has a password, it must be confirmed first. The account can be recovered within a grace period via the account recovery flow.",
    bodyParams: [
      { name: "currentPassword", type: "string", required: false, description: "Required if the account has a password set." },
      { name: "reason", type: "string", required: false, description: "Optional free-text reason for leaving." },
      { name: "locale", type: "string", required: false, description: "en or fr — controls the confirmation email language." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Votre compte a été supprimé. Vous pouvez le récupérer dans les 30 jours." },
    },
    errorExamples: [
      { status: 401, code: "UNAUTHORIZED", message: "Le mot de passe actuel est incorrect." },
    ],
    notes: ["All active sessions are revoked immediately.", "Clears the web session cookies in the response."],
  },
  // --- Account Recovery ---
  {
    slug: "recovery-request",
    method: "POST",
    path: `${BASE}/recovery/request`,
    title: "Request account recovery",
    group: "Account Recovery",
    auth: "none",
    rateLimit: "Request/initiation — per IP and per account",
    description: "Sends a recovery code by email for a deleted account that's still within its recovery grace period.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Email address of the deleted account." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: { message: "Si un compte supprimé existe pour cet e-mail, un code de récupération a été envoyé." },
    },
  },
  {
    slug: "recovery-verify",
    method: "POST",
    path: `${BASE}/recovery/verify`,
    title: "Verify account recovery",
    group: "Account Recovery",
    auth: "none",
    rateLimit: "Credential check — tight, feeds automatic IP blocking",
    description: "Restores a deleted account using the code from POST /recovery/request and signs the user back in.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "Email address of the deleted account." },
      { name: "code", type: "string", required: true, description: "The recovery code from the email." },
      { name: "deviceName", type: "string", required: false, description: "Human-readable device label for the new session." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { user: sampleUser } },
    notes: [
      "If two-factor authentication is enabled, the response is { requiresTotp: true, pendingToken } instead — finish with POST /auth/login/totp.",
    ],
  },
  // --- Phone Number ---
  {
    slug: "phone-request",
    method: "POST",
    path: `${BASE}/phone/request`,
    title: "Request phone verification",
    group: "Phone Number",
    auth: "bearer",
    rateLimit: "Request/initiation",
    description: "Sends a verification code by SMS to add a first phone number to the account.",
    bodyParams: [
      { name: "phone", type: "string", required: true, description: "Phone number to verify, digits only with country code, no leading +." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Un code de vérification a été envoyé par SMS." } },
  },
  {
    slug: "phone-verify",
    method: "POST",
    path: `${BASE}/phone/verify`,
    title: "Verify phone",
    group: "Phone Number",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Confirms the code sent by POST /phone/request.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "The SMS verification code." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "phone-update-request",
    method: "POST",
    path: `${BASE}/phone/update/request`,
    title: "Request phone number change",
    group: "Phone Number",
    auth: "bearer",
    rateLimit: "Request/initiation",
    description: "Sends a verification code by SMS to the new number, ahead of replacing the account's current phone number.",
    bodyParams: [
      { name: "newPhone", type: "string", required: true, description: "The new phone number to switch to." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Un code de vérification a été envoyé par SMS." } },
  },
  {
    slug: "phone-update-verify",
    method: "POST",
    path: `${BASE}/phone/update/verify`,
    title: "Verify phone number change",
    group: "Phone Number",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Confirms the code sent by POST /phone/update/request and replaces the account's phone number.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "The SMS verification code." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  // --- Secondary Email ---
  {
    slug: "secondary-email-request",
    method: "POST",
    path: `${BASE}/email/secondary/request`,
    title: "Add a secondary email",
    group: "Secondary Email",
    auth: "bearer",
    rateLimit: "Request/initiation",
    description: "Sends a verification code to a second email address to add as a backup contact on the account.",
    bodyParams: [
      { name: "email", type: "string", required: true, description: "The secondary email address to add." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { message: "Un code de vérification a été envoyé à votre nouvel email." } },
  },
  {
    slug: "secondary-email-verify",
    method: "POST",
    path: `${BASE}/email/secondary/verify`,
    title: "Verify secondary email",
    group: "Secondary Email",
    auth: "bearer",
    rateLimit: "Credential check",
    description: "Confirms the code sent by POST /email/secondary/request.",
    bodyParams: [
      { name: "code", type: "string", required: true, description: "The verification code from the email." },
      { name: "locale", type: "string", required: false, description: "en or fr." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "secondary-email-delete",
    method: "DELETE",
    path: `${BASE}/email/secondary`,
    title: "Remove secondary email",
    group: "Secondary Email",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Removes the verified secondary email from the account.",
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  // --- Google Account ---
  {
    slug: "google-link",
    method: "POST",
    path: `${BASE}/google/link`,
    title: "Link Google account",
    group: "Google Account",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Links a Google account to the signed-in user, enabling \"Log in with Google\" for this account going forward.",
    bodyParams: [
      { name: "idToken", type: "string", required: true, description: "Google Sign-In ID token from the client SDK." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { linked: true, googleEmail: "aline@gmail.com" } },
  },
  {
    slug: "google-unlink",
    method: "POST",
    path: `${BASE}/google/unlink`,
    title: "Unlink Google account",
    group: "Google Account",
    auth: "bearer",
    rateLimit: "Authenticated action",
    description: "Removes the Google account link. The account must have a password set, or another sign-in method available, before unlinking.",
    successStatus: 200,
    responseExample: { success: true, data: { linked: false } },
    errorExamples: [
      { status: 409, code: "CONFLICT", message: "Définissez un mot de passe avant de dissocier votre compte Google." },
    ],
  },
  // --- Admin ---
  {
    slug: "admin-list-users",
    method: "GET",
    path: BASE,
    title: "List users",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Lists platform users with pagination and optional filters. Staff-only.",
    queryParams: [
      { name: "page", type: "number", required: false, description: "Page number. Defaults to 1." },
      { name: "limit", type: "number", required: false, description: "Results per page, max 100. Defaults to 20." },
      { name: "search", type: "string", required: false, description: "Matches against name and email." },
      { name: "role", type: "string", required: false, description: "Filter by BUYER, SELLER, RIDER, SUPPORT, or ADMIN." },
    ],
    successStatus: 200,
    responseExample: {
      success: true,
      data: {
        users: [sampleUser],
        pagination: { page: 1, limit: 20, total: 1, totalPages: 1 },
      },
    },
  },
  {
    slug: "admin-get-user",
    method: "GET",
    path: `${BASE}/:id`,
    title: "Get user detail",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Session",
    description: "Returns full detail for a single user, for staff review. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "admin-block-user",
    method: "POST",
    path: `${BASE}/:id/block`,
    title: "Block user",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Blocks a user account, preventing sign-in. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [{ name: "reason", type: "string", required: true, description: "Reason shown internally and referenced in the notification sent to the user." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleUser, isBlocked: true } },
  },
  {
    slug: "admin-unblock-user",
    method: "POST",
    path: `${BASE}/:id/unblock`,
    title: "Unblock user",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Reverses a block, restoring the user's ability to sign in. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Optional internal note." }],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleUser, isBlocked: false } },
  },
  {
    slug: "admin-force-logout",
    method: "POST",
    path: `${BASE}/:id/force-logout`,
    title: "Force logout",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Revokes one session, or every session, on a user's account. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [
      { name: "sessionId", type: "string", required: false, description: "Revoke only this session. Omit to revoke all of the user's sessions." },
      { name: "reason", type: "string", required: false, description: "Optional internal note." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { revokedCount: 1 } },
  },
  {
    slug: "admin-verify-email",
    method: "POST",
    path: `${BASE}/:id/verify-email`,
    title: "Manually verify email",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Marks one of a user's email addresses as verified without the user completing the code flow. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [{ name: "emailId", type: "string", required: true, description: "ID of the email address to mark verified." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "admin-verify-phone",
    method: "POST",
    path: `${BASE}/:id/verify-phone`,
    title: "Manually verify phone",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN", "SUPPORT"],
    rateLimit: "Authenticated action",
    description: "Marks a user's phone number as verified without the user completing the code flow. Staff-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "admin-delete-user",
    method: "POST",
    path: `${BASE}/:id/delete`,
    title: "Delete user",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Deletes a user account on the platform's behalf — for policy violations or support-driven closures. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Reason recorded and referenced in the notification sent to the user." }],
    successStatus: 200,
    responseExample: { success: true, data: { deleted: true } },
  },
  {
    slug: "admin-restore-user",
    method: "POST",
    path: `${BASE}/:id/restore`,
    title: "Restore user",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Reverses an admin-initiated deletion, restoring the account. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [{ name: "reason", type: "string", required: false, description: "Optional internal note." }],
    successStatus: 200,
    responseExample: { success: true, data: sampleUser },
  },
  {
    slug: "admin-change-role",
    method: "POST",
    path: `${BASE}/:id/role`,
    title: "Change user role",
    group: "Admin",
    auth: "bearer",
    roles: ["ADMIN"],
    rateLimit: "Authenticated action",
    description: "Changes a user's platform role. Admin-only.",
    pathParams: [{ name: "id", type: "string", required: true, description: "User ID." }],
    bodyParams: [
      { name: "role", type: "string", required: true, description: "One of BUYER, SELLER, RIDER, SUPPORT, ADMIN." },
      { name: "reason", type: "string", required: false, description: "Optional internal note." },
    ],
    successStatus: 200,
    responseExample: { success: true, data: { ...sampleUser, role: "SUPPORT" } },
  },
];

