const PAYOUT_SECURITY_CONFIG = {
  OTP_RESEND_COOLDOWN_SECONDS: 60,
  OTP_MAX_FAILED_ATTEMPTS: 5,
  OTP_LOCKOUT_MINUTES: 15,
  CONFIRM_LOCK_TTL_MS: 30 * 1000,
  ADMIN_DAILY_PAYOUT_MAX_COUNT: 20,
  ADMIN_DAILY_PAYOUT_AMOUNT_LIMITS: {
    USD: 10_000,
    CDF: 20_000_000,
    RWF: 2_000_000,
  },
};

module.exports = { PAYOUT_SECURITY_CONFIG };
