const WALLET_SETTINGS_CONFIG = {
  SUPPORTED_CURRENCIES: ["USD", "CDF", "RWF"],

  PAYOUT_SCHEDULES: ["MANUAL", "WEEKLY", "MONTHLY"],

  DEFAULT_MINIMUM_PAYOUT_AMOUNT: {
    USD: 5,
    CDF: 10000,
    RWF: 5000,
  },

  MAX_MINIMUM_PAYOUT_AMOUNT: {
    USD: 1000,
    CDF: 2000000,
    RWF: 1000000,
  },
};

module.exports = { WALLET_SETTINGS_CONFIG };
