const SUPPORTED_CURRENCIES = ["USD", "CDF"];

const SUPPORTED_PAYOUT_PROVIDERS = ["MBIYOPAY"];
const DEFAULT_PAYOUT_PROVIDER = "MBIYOPAY";

const TRANSACTION_TYPES = [
  "ORDER_CREDIT",
  "PAYOUT_DEBIT",
  "REFUND_DEBIT",
  "ADJUSTMENT",
];

const TRANSACTION_STATUSES = ["PENDING", "COMPLETED", "FAILED"];

const WALLET_CONFIG = {
  SUPPORTED_CURRENCIES,

  SUPPORTED_PAYOUT_PROVIDERS,
  DEFAULT_PAYOUT_PROVIDER,

  TRANSACTION_TYPES,
  TRANSACTION_STATUSES,

  DEFAULT_LIST_LIMIT: 20,
  MAX_LIST_LIMIT: 100,

  PAYOUT_LOCK_PREFIX: "wallet-payout:",
  PAYOUT_LOCK_TTL_MS: 30 * 1000,

  PAYOUT_OTP_CACHE_PREFIX: "wallet-payout-otp:",
  PAYOUT_OTP_TTL_MINUTES: 5,
  PAYOUT_OTP_RESEND_COOLDOWN_SECONDS: 30,

  PENDING_PAYOUT_RECONCILE_AFTER_MINUTES: 15,

  MAX_PAYOUT_RETRIES: 3,
  PAYOUT_RETRY_DELAY_MINUTES: 240,

  DAILY_PAYOUT_LIMITS: {
    USD: 1000,
    CDF: 2_000_000,
    RWF: 2_000_000,
  },
};

module.exports = { WALLET_CONFIG };
