const {
  BILLING_CYCLES,
  SUPPORTED_CURRENCIES,
} = require("../constants/plan.constants");

const PLAN_CONFIG = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 40,

  MIN_MAX_PRODUCTS: 1,
  MIN_MAX_PHOTOS_PER_PRODUCT: 1,
  MAX_PHOTOS_PER_PRODUCT_CAP: 20,

  REQUIRED_BILLING_CYCLES: Object.values(BILLING_CYCLES),
  REQUIRED_CURRENCIES: SUPPORTED_CURRENCIES,

  EXPECTED_YEARLY_DISCOUNT_PERCENT: 15,
};

module.exports = { PLAN_CONFIG };
