blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/SwiftGomaApp/SwiftGoma/discussions
    about: For general questions that aren't a bug or feature request.
