const INVOICING_CONFIG = {
  DOCUMENT_NUMBER_PREFIXES: {
    INVOICE: "SWG-INV",
    RECEIPT: "SWG-REC",
    PAYOUT_RECEIPT: "SWG-PAYOUT",
  },
  DOCUMENT_NUMBER_PADDING: 6,
  CLOUDINARY_FOLDER: "swiftgoma/invoices",
};

module.exports = { INVOICING_CONFIG };
