const HERO_SLIDE_CONFIG = {
  ALLOWED_ROLES: ["SELLER", "BUYER", "RIDER", "PAYMENT"],

  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 80,

  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 240,

  SEARCH_PLACEHOLDER_MIN_LENGTH: 3,
  SEARCH_PLACEHOLDER_MAX_LENGTH: 80,

  ROLE_TO_CLIENT: {
    SELLER: "seller",
    BUYER: "buyer",
    RIDER: "rider",
    PAYMENT: "payment",
  },
};

module.exports = { HERO_SLIDE_CONFIG };
