const NOTIFICATION_TYPES = {
  ORDER_STATUS: "ORDER_STATUS",
  PAYMENT: "PAYMENT",
  ACCOUNT_SECURITY: "ACCOUNT_SECURITY",
  PROMO: "PROMO",
  SELLER_ONBOARDING: "SELLER_ONBOARDING",
  SUPPORT: "SUPPORT",
  SYSTEM: "SYSTEM",
};
const FORCED_NOTIFICATION_TYPES = [NOTIFICATION_TYPES.ACCOUNT_SECURITY];

module.exports = { NOTIFICATION_TYPES, FORCED_NOTIFICATION_TYPES };
